### ISSUE TITLE
Deploy patched versions of OpenStack code

### ISSUE THREAD

**Issue by tzumainn** [CCI-MOC/esi#101]
cinder-volume

* rbd-iscsi-client
* multipath changes

neutron-server

* various networking-ansible related code (some may be packaged now)
* new switch driver

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200974017553249/1200974071245284) by [Unito](https://www.unito.io)

**Comment by larsks** [comment]
Part of https://github.com/CCI-MOC/esi/issues/94
