### ISSUE TITLE
Write an article about ESI for the RHRQ

### ISSUE THREAD

**Issue by gagansk** [CCI-MOC/esi#104]
* 1,000-2,000 words is the ideal range—850 words is a bare minimum.
* Include Charts and graphs. 

DoD:

* The article should be presented to the Engineering team for their approval.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200974017553249/1200974040708870) by [Unito](https://www.unito.io)

**Comment by gagansk** [comment]
RHRQ draft is [here](https://docs.google.com/document/d/1BmvwNN55sNo8P5XaBChCJTmqr9PDeBK3iL01G4UVf3k/edit?usp=sharing).

**Comment by gagansk** [comment]
@tzumainn @larsks Can you please review the document and add your comments? 

FYI, the article will be public in late October. So, I am have assumed the production deployment will be ready and we will be exploring the ways of running OCP on top of the leased nodes by that time.

**Comment by joachimweyl** [comment]
@gagansk what is the priority on this?

**Comment by joachimweyl** [comment]
done.
