### ISSUE TITLE
Track Keylime Certificate Flushing Issue

### ISSUE THREAD

**Issue by tzumainn** [CCI-MOC/esi#109]
Once keylime/keylime#550 is fixed we can remove the needed configuration workaround.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200974017553249/1200974069566384) by [Unito](https://www.unito.io)

**Comment by joachimweyl** [comment]
https://github.com/keylime/keylime/issues/550 was fixed
@tzumainn what are the next steps?
