### ISSUE TITLE
Test user-created networks

### ISSUE THREAD

**Issue by tzumainn** [CCI-MOC/esi#118]
User created networks should be able to grab a vlan. They should also be limited by quota.

**Comment by tzumainn** [comment]
@naved001 Users do not pick their vlans, right? I think OpenStack arbitrarily assigns them from the available pool.

**Comment by naved001** [comment]
@tzumainn yes, that's right. Should be arbitrarily assigned from a pool. The administrators should be able to define what the available pool should be.

**Comment by tzumainn** [comment]
This all works as expected:

* similar quota management as with volumes (openstack quota show, openstack quota set --networks <number> <project id>
* vlan range controlled in ml2_conf.ini
