### ISSUE TITLE
Download Allowlist from generic source

### ISSUE THREAD

**Issue by ljmcgann** [CCI-MOC/esi#126]
Implement a way to download an allowlist and any other keylime files to the ironic controller to start attestation. 

This work was originally implemented and submitted last sprint using a Swift based solution, but after the Ironic midcycle, it was determined that the implementation we take would have to be more generic.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200974017553249/1200974037460907) by [Unito](https://www.unito.io)

**Comment by tzumainn** [comment]
Going a different path
