### ISSUE TITLE
Write spec for Ironic power intermediary API and submit to upstream Ironic team for review.

### ISSUE THREAD

**Issue by samuel-zuk** [CCI-MOC/esi#130]
Branches off of #72.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200974017553249/1200974034891742) by [Unito](https://www.unito.io)

**Comment by tzumainn** [comment]
Original spec: https://review.opendev.org/c/openstack/ironic-specs/+/764801

**Comment by samuel-zuk** [comment]
[First draft is live and ready for review!](https://github.com/samuel-zuk/ironic-specs/pull/1)

**Comment by samuel-zuk** [comment]
[Live for review by Ironic upstream team](https://review.opendev.org/c/openstack/ironic-specs/+/808818)
