### ISSUE TITLE
Test Tenant Keylime Usage (completely outside of Ironic)

### ISSUE THREAD

**Issue by tzumainn** [CCI-MOC/esi#138]
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200974017553249/1200975080862522) by [Unito](https://www.unito.io)

**Comment by tzumainn** [comment]
https://github.com/CCI-MOC/esi/pull/116

**Comment by joachimweyl** [comment]
@DanNiESh I noticed this is in the `Done` row in the Project `ESI Taskboard` but it is still open. What are the next steps on this?

**Comment by joachimweyl** [comment]
no longer needed
