### ISSUE TITLE
Explore ESI neutron port cleanup

### ISSUE THREAD

**Issue by tzumainn** [CCI-MOC/esi#146]
Neutron port cleanup.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200974017553249/1201058043321208) by [Unito](https://www.unito.io)

**Comment by tzumainn** [comment]
If we auto-generate port names, maybe we can see if the port name already exists and is not in use; and if so, use it?

**Comment by DanNiESh** [comment]
"metalsmith undeploy <node>" could clean up the neutron port.

**Comment by tzumainn** [comment]
I think that's fine for metalsmith; what about if someone uses 'esi node network attach' or some other esi prompt?

**Comment by DanNiESh** [comment]
> If we auto-generate port names, maybe we can see if the port name already exists and is not in use; and if so, use it?

Can we list ports before creating ports? Use {network, status} filter to find out available ports. But the ports' names could contain other nodes' names.

**Comment by tzumainn** [comment]
Yep, that should be possible! But you're right - the port names include the node names. I wonder if it's possible to instead create a port with just the network name and some sort of metadata indicating that it was auto-generated, which allows it to be used again if the user wants to use that network again?

**Comment by DanNiESh** [comment]
> Yep, that should be possible! But you're right - the port names include the node names. I wonder if it's possible to instead create a port with just the network name and some sort of metadata indicating that it was auto-generated, which allows it to be used again if the user wants to use that network again?

For example "provisioning-auto"? I think neutron will extend the port name if it's duplicated.

**Comment by tzumainn** [comment]
I wonder if it makes sense to have the project name as well, so an admin can easily distinguish between who created what port (and because we don't want project2 to use a port that project1 created). I think neutron flat out allows duplicate port names.
