### ISSUE TITLE
Create System Test Scripts

### ISSUE THREAD

**Issue by tzumainn** [CCI-MOC/esi#151]
System tests documented here:

https://docs.google.com/document/d/1pdAn_RnATBryebs9sk_6PvKHDp6Bd4NYnMlIPdYXGOA/edit

This can be scripts that are manually run.

**Comment by joachimweyl** [comment]
@tzumainn as this is part of the current sprint please add ZH estimate.

**Comment by tzumainn** [comment]
Done!

**Comment by tzumainn** [comment]
Closing as this is superceded by the Rally framework
