### ISSUE TITLE
Keylime in PYPI

### ISSUE THREAD

**Issue by ljmcgann** [CCI-MOC/esi#156]
Keylime needs to be registered in pypi. Stuck waiting on Keylime people to do it as we can't be maintainers.

**Comment by ljmcgann** [comment]
Thore Sommer of Keylime and I have talked over this and agree it would be useful to see Keylime in PyPI. However, we are at the whim of Keylime maintainers to make the account and register Keylime. Once Keylime is in PyPI, the Ironic code will work as is, save for any api version updates the patch needs.

**Comment by joachimweyl** [comment]
@tzumainn Leo is no longer on this project, what would you like to do with this issue?

**Comment by tzumainn** [comment]
I'll close it
