### ISSUE TITLE
Demo ESI for NERC engineers

### ISSUE THREAD

**Issue by hpdempsey** [CCI-MOC/esi#160]
BU and Harvard IT have allocated some time for NERC engineers to work with us.  Step one is to demo the new ESI functions using the CLI in the development environment (since that is the only current environment).

This demo should focus more on how we think ESI can be used for admins managing bare metal hardware (moving it from ownership by one group to another) and less on the end-user leasing functions.  NERC folks would like to be able to play with the CLI in the development environment on their own later if that is feasible, so they can give better feedback.  For the demo, we should talk about ESI functions and how we eventually see them integrating with other functions in the data center (provisioning, reporting etc.).  The reason for this "speculation" to be part of the demo is because integration with multiple systems is a primary concern for NERC (see the multiple integration issues in Operate First with the NERC label, for example).

**Comment by tzumainn** [comment]
Is there a time when this demo is expected to happen?

**Comment by hpdempsey** [comment]
Justin Riley has been assigned from NERC to watch this demo and to give us feedback on the CLI and workflow and how that would fit in to what the NERC expects to do with ESI.  This in turn, should result in issues or feature requests from NERC that we can incorporate into our sprint planning.   If the pilot ESI system will be available soon (<2 weeks), then the demo should happen right after we've checked out the pilot system.  If we don't think it will be available soon, we should do this demo on the dev system to surface any really big issues quickly, and then do a follow-up demo on the pilot system, which Justin should be able to access and use himself once we've got it set up.

**Comment by hpdempsey** [comment]
NERC has asked that we also invite Augustin to this ESI demo, so here are both emails:  

justinriley@g.harvard.edu Manager of Cloud and Software as Infrastructure, Harvard
augustin@bu.edu  (Augstine Abaris)  Lead Research Computing Systems Engineer at BU

Please send them the readthedocs link too, in case they want to take a look at that before/after the demo.

**Comment by hpdempsey** [comment]
As an extra bit of info, Scott and Wayne from NERC are working on getting network connectivity for some small number of bare metal machines so we can do ESI testing with NERC.  Justin will probably be the one who works with us on this when it is ready.  Michael also says that new bare metal machines are going to be added to MOC in Jan and those could also be available for testing, if we decide to use them.  Mentioning this because of the original request in this issue to focus the demo on this type of ESI use, more than general hardware leasing uses we have discussed before.

**Comment by tzumainn** [comment]
Done - there are some follow up tasks that I'll create.
