### ISSUE TITLE
Give NERC devs demo access

### ISSUE THREAD

**Issue by tzumainn** [CCI-MOC/esi#164]

**Comment by tzumainn** [comment]
@naved001 it looks like we may want to grant the NERC folks access to the demo server. I can set up accounts on the server, but what's the best way for them to access it? I assume they need a kumo account... ?

**Comment by naved001** [comment]
yeah, they'll access that from kumo. Who all need access and what's their public SSH keys?

**Comment by tzumainn** [comment]
Is it possible to create a generic "nerc-demo" account and give me access, with me adding their keys later?

**Comment by naved001** [comment]
sounds good, I messaged you on google chat.

**Comment by tzumainn** [comment]
Thanks! Everything looks like it's all set now.
