### ISSUE TITLE
Documentation needs revision to be clear about required vs. optional parts of ESI

### ISSUE THREAD

**Issue by hpdempsey** [CCI-MOC/esi#166]
Documentaion should clearly indicate what MUST be included from ESI (Ironic, Neutron, basic leasing parts) vs. what is optional (attestation, provisioning....).  This is important to make it easier for new groups who might be interested in ESI to determine what is necessary to start using ESI vs. what they can do later (or not at all)

**Comment by tzumainn** [comment]
@hpdempsey Do you think the text on https://esi.readthedocs.io/en/latest/install/index.html is enough? I tried to make it as clear and succinct as possible, without going into details about how one installs OpenStack in the first place, since there's a lot of different installers.

**Comment by joachimweyl** [comment]
@hpdempsey what is the priority on this issue? is it ready to be closed? Can I offer my reviewing skills on this documentation?

**Comment by hpdempsey** [comment]
Yes, the documentation addressed this issue, which should be closed.  Just
lost track of it.
