### ISSUE TITLE
Investigate methods of integrating external authentication with ESI

### ISSUE THREAD

**Issue by tzumainn** [CCI-MOC/esi#167]
NERC uses coldfront, etc.

What does Keystone allow?

Looks like people have worked with both coldfront and openstack before, so maybe this is a solved issue?

**Comment by naved001** [comment]
@knikolla maybe the best person to answer this since he's currently involved with coldfront and keystone afaik.

**Comment by knikolla** [comment]
ColdFront is only responsible for the resource allocation process (creating projects, users, and assigning roles to users on projects). It doesn't deal with authentication. We already have a working implementation of ColdFront creating projects and users in Keystone.

For authentication, the NERC is using OpenID Connect, which Keystone already has support for.

**Comment by DanNiESh** [comment]
This is a duplicate issue: https://github.com/CCI-MOC/esi/issues/238
