### ISSUE TITLE
Define network requirements for esi pilot deployment

### ISSUE THREAD

**Issue by DanNiESh** [CCI-MOC/esi#176]
- [ ] All nodes should be in some sort of undercloud provisioning network.
- [ ] Undercloud node should have a public network to download packages and be ssh'able.
- [ ] Overcloud nodes should have a public network and be ssh'able?
- [ ] Undercloud node should have access to ipmi network.
- [ ] All nodes should have another interface for provisioning network.

**Comment by naved001** [comment]
@DanNiESh could you tell me which nodes are undercloud and which are overcloud? I think oct4-0 is undercloud?

**Comment by DanNiESh** [comment]
> @DanNiESh could you tell me which nodes are undercloud and which are overcloud? I think oct4-0 is undercloud?

Yes. oct-4-0 is undercloud. oct-4-03, oct-4-04, oct-4-05 are overcloud nodes.

**Comment by naved001** [comment]
@larsks I noticed that in [this network document](https://docs.massopen.cloud/en/latest/clusters/kaizen2/Kaizen-2.html#public-neu-vlan-127) you have allocated the following IPs:

```
129.10.5.140     esi-undercloud.massopen.cloud
129.10.5.141     esi-controller-0.massopen.cloud
129.10.5.142     esi-controller-1.massopen.cloud
129.10.5.143     esi-controller-2.massopen.cloud
```

If those aren't being used for any test cluster, can we use these for the ESI undercloud/overcloud nodes?

**Comment by larsks** [comment]
@naved001 you can go ahead and use those, sure.

**Comment by naved001** [comment]
I have configured the networks.

```
oct-dell-4#show run inter vlan 208
!
interface Vlan 208
 description ESI-control-plane
 no ip address
 tagged TenGigabitEthernet 1/18
 untagged TenGigabitEthernet 1/13-1/15
 no shutdown
oct-dell-4#show run inter vlan 127
!
interface Vlan 127
 description MOC-neu-public
 name MOC-NEU-PUBLIC
 no ip address
 tagged TenGigabitEthernet 1/13-1/15
 tagged Port-channel 1
 untagged TenGigabitEthernet 1/18
 shutdown
```

oct4-0 is on the public network (native, untagged), and the ESI private network is tagged so you'll need to create VLAN interface for that. The VLAN ID is 208.

oct4-{3,4,5} are untagged on the private ESI network, and tagged on the public network.

There's no DHCP on the public network 127, so you should statically configure the IPs on all the nodes (mentioned in the previous comment). You could even use those hostnames since they will resolve to the correct IP. The gateway for this network is at `129.10.5.1`, and subnet mask is `255.255.255.0` or `/24`.

**Comment by DanNiESh** [comment]
We need to config undercloud node to have access to ipmi network. @naved001

**Comment by DanNiESh** [comment]
After reading the doc [minimum-system-requirements](https://docs.openstack.org/project-deploy-guide/tripleo-docs/latest/environments/baremetal.html) (network section and the diagram), I realized that we need a provisioning network NIC and a public network NIC for each node. For undercloud node, I use eth4 for public network access and also bridge it to br-ctlplane. As the result, the machine loses internet connectivity during undercloud installation.  @naved001

**Comment by naved001** [comment]
This will have to wait until the next data center visit (sometime next week) at that point the nodes will be dual connected.

**Comment by naved001** [comment]
@DanNiESh I have reconfigured the network interfaces now that we have dual connections.

OCT-4-0's 1st interface (connected to switchport 1/18) is untagged on the public network (and that already works, that's how we SSH), and it's 2nd port (switchport 1/20) is on the ESI provisioning network. I configured that interface on the host (so you won't see the VLAN interface).

The overloud hosts 1st interfaces are untagged on the provisioning network, and the 2nd interfaces are untagged on the public network. 

For OCT-4-0 to access the IPMI network, we will have to tag the IPMI vlan on 1 of the interfaces, let me know which interface you'd prefer. 

Posting this switch config for future me (or for anyone to notice any weirdness)
```
oct-dell-4#show running-config interface vlan 127
!
interface Vlan 127
 description MOC-neu-public
 name MOC-NEU-PUBLIC
 no ip address
 tagged Port-channel 1
 untagged TenGigabitEthernet 1/18,1/21-1/23
 shutdown
oct-dell-4#show running-config interface vlan 208
!
interface Vlan 208
 description ESI-control-plane
 no ip address
 untagged TenGigabitEthernet 1/13-1/15,1/20
 no shutdown
 ```

**Comment by naved001** [comment]
I have configured the 1st interface of oct-4-0 to be on the IPMI network, let me know if we need to move it to the other interface.

**Comment by DanNiESh** [comment]
> IPMI



> I have configured the 1st interface of oct-4-0 to be on the IPMI network, let me know if we need to move it to the other interface.

I think it's fine! Thanks!

**Comment by DanNiESh** [comment]
> I have configured the 1st interface of oct-4-0 to be on the IPMI network, let me know if we need to move it to the other interface.

@naved001, is "enp3s0f1np1" the provisioning network interface?

**Comment by naved001** [comment]
> is "enp3s0f1np1" the provisioning network interface?

yes. I think that's what you'll put on the bridge.
