### ISSUE TITLE
Create Document Detailing NERC/ESI Plans

### ISSUE THREAD

**Issue by tzumainn** [CCI-MOC/esi#177]
This document should address immediate NERC concerns, as well as speculate about future directions of interest to NERC.

**Comment by tzumainn** [comment]
https://docs.google.com/document/d/1L29m9krGx2zlCAEiwtKxBc6_cybDaVSMC5b18Jw73gA/edit#

**Comment by joachimweyl** [comment]
@gagansk is this a duplicate of https://github.com/CCI-MOC/esi/issues/348

**Comment by joachimweyl** [comment]
closing as dup of https://github.com/CCI-MOC/esi/issues/348
