### ISSUE TITLE
Investigate Ironic rescue operations

### ISSUE THREAD

**Issue by tzumainn** [CCI-MOC/esi#193]

**Comment by mnbatra** [comment]
Looking into the rescue operations doc https://docs.openstack.org/ironic/rocky/admin/rescue.html and how it can put into use for ESI

**Comment by mnbatra** [comment]
What rescue operation can be used for :

1. OS related failures, boot from an iso
2. File system corruption, Hard disk partial corruption
3. Blocked by the firewall, networking issues
4. Full System Reset to default state
5. Forgot machine password or locked out of machine for any reason

**Comment by mnbatra** [comment]
What rescue operation CANNOT be used for :

1. Critical firmware failures i.e.. Drivers compromised or corrupted for example: BMC, BIOS, DRAC changed.
2. Cannot network boot, that will put a machine in Rescue Fail
3. Major hardware failures for example: Controller shorted, processor crashed, hard drive bricked

**Comment by mnbatra** [comment]
Manual testing and verification in progress

**Comment by mnbatra** [comment]
Rescue operation worked good for simple tasks described above. Detailed steps and frequent errors/fixes can be found here:
https://docs.google.com/document/d/1ebF1ulW4Dvlj0VfttioLMF5zUQ4QQXtN6H8YXRXmMkI/edit

Quite useful tool for lessees.
