### ISSUE TITLE
Customize overcloud networks 

### ISSUE THREAD

**Issue by DanNiESh** [CCI-MOC/esi#196]
Use this heat template to customize overcloud networks:https://opendev.org/openstack/tripleo-heat-templates/src/branch/master/network-data-samples/default-network-isolation.yaml. 

- Which networks are needed? Tenant is used for compute workloads, do we need it?
- Allocate VLAN IDs to those networks.
- External network? IP and VLAN

**Comment by naved001** [comment]
@larsks @DanNiESh questions:

1. Do you think we could skip setting up the tenant network for this ESI instance?
2. Would we need to add storage network and connect this to our ceph cluster? If yes, what sort of ceph configuration would be required?
3. External network would be where we get floating IPs from? Are there any specific requirements for such a network.

Thanks!

**Comment by tzumainn** [comment]
My opinions:

1. I'm not entiiiiirely sure what a tenant network is for; I think Danni mentioned Nova VMs. If so, we can definitely skip it, and worst case revisit if it turns out we need it.
2. I'm guessing that boot-from-volume is something we'd like to eventually demonstrate - but I don't know it has to be now. If this complicates things, I'd personally rather skip it for now and upgrade the environment later.
3. I admit I don't even know what "requirements" covers here; we do want the nodes to have external connectivity though!

**Comment by larsks** [comment]
> I'm not entiiiiirely sure what a tenant network is for;

In a typical Nova-based openstack deployment, the tenant network is dedicated to all the VXLAN generated subnets that result from tenants creating network via e.g. `openstack network create`. With baremetal based deployments, we'll be using VLAN networks, so there's no need to dedicate a specific L2 network (because each tenant-generated network will be it's own separate L2 vlan).

> Do you think we could skip setting up the tenant network for this ESI instance?

So yes, probably.

> Would we need to add storage network and connect this to our ceph cluster? If yes, what sort of ceph configuration would be required?

We will want Cinder in order to support boot-from-volume, and we'll need backing store for Glance, I think. That probably just means a dedicated ceph pool for this openstack environment (or possibly multiple pools; I know that previously we were using "one pool per  clustser", but I would tend to separate "ceph volumes" from "glance images", for example).

> External network would be where we get floating IPs from? Are there any specific requirements for such a network.

I don't think there are particular requirements; we'll need a range of free addresses, but I think we have that.

**Comment by naved001** [comment]
> 
> 
>     External network would be where we get floating IPs from? Are there any specific requirements for such a network.
> 
> I don't think there are particular requirements; we'll need a range of free addresses, but I think we have that.

Now that I think about it, since this openstack is for baremetal nodes, can't the nodes just connect directly to the right VLAN with an external network?

**Comment by tzumainn** [comment]
> > ```
> > External network would be where we get floating IPs from? Are there any specific requirements for such a network.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I don't think there are particular requirements; we'll need a range of free addresses, but I think we have that.
> 
> Now that I think about it, since this openstack is for baremetal nodes, can't the nodes just connect directly to the right VLAN with an external network?

Wouldn't they still need a pool of floating IPs to be assigned an address?

**Comment by larsks** [comment]
> Wouldn't they still need a pool of floating IPs to be assigned an address?

There are two different ways of exposing machines in openstack to a public network.

Using floating ips, the machines is connected only to a private network. A "router" handles NAT between the public addresses and the private network.

Alternately, a machine may be directly attached to a provider network -- that is, a predefined L2 network with an assigned public address range. In this case, they would need to rely on either DHCP or static assignment to obtain an ip address.

The advantage to the floating ip model is that we retain control of the network (people can use only the floating ips they've acquired through openstack). If someone is directly attached to a public VLAN, there's nothing preventing them from accidentally (or maliciously) reaking havoc.

**Comment by larsks** [comment]
PS I don't know for certain that floating ips work in a baremetal world, but it seems like they should. Something to check out!

**Comment by naved001** [comment]
@DanNiESh 

The IP address range to be used for external network is being documented here: https://github.com/CCI-MOC/documentation/pull/111/files

The overcloud nodes' second NICs are now tagged with VLAN 3801 which is the external network.
```
Te 1/21              oct4-01-2    Up     10000 Mbit   Full   127,3801
Te 1/22              oct4-02-2    Down   Auto         Auto   127,3801
Te 1/23              oct4-03-2    Down   Auto         Auto   127,3801
```

Their first NICs are tagged with the ceph network VLAN 250 and there's DHCP on that network.
```
Te 1/15              oct4-03-1    Down   Auto         Auto   208,250
Te 1/16              oct4-02-1    Down   Auto         Auto   208,250
Te 1/17              oct4-01-1    Up     10000 Mbit   Full   208,250
```

**Comment by naved001** [comment]
@DanNiESh @tzumainn 

We got two more nodes: oct4-04 and oct-05, dual connected.

```
oct-dell-4#show interfaces status |grep oct4-04
Te 1/14              oct4-04-1    Down   Auto         Auto   208,250
Te 1/24              oct4-04-2    Down   Auto         Auto   127,3801
oct-dell-4#show interfaces status |grep oct4-05
Te 1/13              oct4-05-1    Up     10000 Mbit   Full   208,250
Te 1/25              oct4-05-2    Up     10000 Mbit   Full   127,3801
```

They are connected the same way as the other overcloud nodes. I updated the firmware of the NICs too.

**Comment by naved001** [comment]
@DanNiESh is there anything else that we need to do here or can we close this issue?

**Comment by DanNiESh** [comment]
We can close it now.

**Comment by naved001** [comment]
@DanNiESh @tzumainn I have added the VLAN (ID 207) for switch management on the interface that carries public network (129.10.5.X, VLAN 127)

Here's the updated switch configuration:

```
oct-dell-4#show interfaces status |grep oct4-00
Te 1/18              oct4-00-1    Up     10000 Mbit   Full   127,207,911
Te 1/20              oct4-00-2    Up     10000 Mbit   Full   208
oct-dell-4#show interfaces status |grep oct4-01
Te 1/17              oct4-01-1    Up     10000 Mbit   Full   208,250
Te 1/21              oct4-01-2    Up     10000 Mbit   Full   127,207,3801
oct-dell-4#show interfaces status |grep oct4-03
Te 1/15              oct4-03-1    Up     10000 Mbit   Full   208,250
Te 1/23              oct4-03-2    Up     10000 Mbit   Full   127,207,3801
oct-dell-4#show interfaces status |grep oct4-04
Te 1/14              oct4-04-1    Up     10000 Mbit   Full   208,250
Te 1/24              oct4-04-2    Up     10000 Mbit   Full   127,207,3801
```

I created the VLAN interface `enp3s0f0np0.207` on the undercloud host and that can reach the switch. It's statically configured. 
```
ONBOOT=yes
VLAN=yes
BOOTPROTO=none
NAME=enp3s0f0np0.207
IPADDR=10.1.0.2
PREFIX=24
```


You'll need to create the VLAN interface on the overcloud nodes. Please use the IPs `10.1.0.3`, `10.1.0.4` and `10.1.0.5` with prefix set to 24.
