### ISSUE TITLE
Investigate Ironic cleaning in depth

### ISSUE THREAD

**Issue by tzumainn** [CCI-MOC/esi#197]
Look into what it does by default; and what options are available.

**Comment by mnbatra** [comment]
Initial progress can be tracked here
 https://docs.google.com/document/d/1D0E4O2Gt0Os28XLot1P5MRWl7CuUuoLol0zBO7isQ9A/edit?usp=sharing

**Comment by mnbatra** [comment]
Investigated the use cases for esi. Now compiling a draft with useful insights
