### ISSUE TITLE
Setup Ceph for Pilot Environment

### ISSUE THREAD

**Issue by tzumainn** [CCI-MOC/esi#213]
The ESI pilot deployment would ideally be able to boot from volume.

**Comment by tzumainn** [comment]
@larsks I'm not sure what the practical considerations might be here regarding requirements - would you have some idea?

**Comment by larsks** [comment]
@tzumainn we can use the existing MOC ceph service, but we'll need some ceph/iscsi gateways. @naved001 will know if they already exist or if we need to deploy new ones.

**Comment by naved001** [comment]
I'll need to deploy the iSCSI gateways. 

And for openstack I think I'll create 2 pools, one for volumes (cinder) and another for images (glance), is that all?

**Comment by naved001** [comment]
@larsks looks like our current openstack deployment is using a single pool `ostack2` for both images and cinder. @tzumainn I created a ceph pool `esi-volumes` to use with ESI. If another pool is strictly required for glance images I'd be happy to create that too.

**Comment by naved001** [comment]
I created a user `esi` and generated a keyring that will allow it to access only the `esi-volumes` pool on the ceph cluster.

**Comment by naved001** [comment]
I finished setting up 2 iSCSI gateways on a new iSCSI network. I tested mounting a volume and that worked fine.

**Comment by tzumainn** [comment]
Thanks! We'll give it a whirl.

**Comment by naved001** [comment]
I have documented the iSCSI gateway config on this issue: https://github.com/CCI-MOC/ops-issues/issues/85#issuecomment-1102709286

**Comment by joachimweyl** [comment]
@tzumainn will close when testing done.

**Comment by tzumainn** [comment]
Yep! We've successfully tested this in a 1 controller setup; just waiting to deploy HA to test one final time.
