### ISSUE TITLE
Coordinate access to additional baremetal nodes for ESI Pilot

### ISSUE THREAD

**Issue by tzumainn** [CCI-MOC/esi#216]
Coordinate access to additional bare-metal nodes for ESI Pilot

**Comment by naved001** [comment]
@tzumainn what more additional hardware do we need? Right now, the hardware in OCT4 rack is assigned to the ESI project. That rack has 13 nodes, out of which 1 is undercloud and 3 are overclouds; that leaves us with 9 nodes for actual baremetal usage.

**Comment by tzumainn** [comment]
@naved001 Ah, we may as well use those 9 for the overcloud baremetal inventory, unless there's a reason they need to be saved for something else... ?

**Comment by naved001** [comment]
@tzumainn They don't need to be saved for anything else; those are allocated for the ESI project.

**Comment by tzumainn** [comment]
Okay! I think that's a reasonable start; I have no idea what the longer term plans are though. I think we just need the IPMI and node's port information on the switch; I guess they also have to be on the IPMI network. @DanNiESh anything else?

**Comment by naved001** [comment]
This google sheet has the list of nodes: https://docs.google.com/spreadsheets/d/1V4_24MEQvpQaEIWOY9CT3zMeu_7llBagkYRxAIsJ1a4/edit#gid=748212895

Should be on the sheet labeled OCT4. The nodes allocated for ESI are from OCT4-00 to OCT4-17.  That sheet has some nodes like INTEL-{1,2,3,4} and those are NOT allocated to ESI.

The switchport for each node is in column Q. The IPMI address for node OCT4-X is 10.2.4.X. The overcloud nodes can access the IPMI network of the nodes using VLAN 911 (it might already be attached).

**Comment by tzumainn** [comment]
Great! We'll test this out when we eventually redeploy the overcloud. Thanks!

**Comment by tzumainn** [comment]
Not yet - we're still in the process of deploying the overcloud, and won't be able to test this out until then.

**Comment by tzumainn** [comment]
This is basically done; a few nodes have issues, but that remediation is being tracked separately
