### ISSUE TITLE
Production setup (Hardware dependencies) 

### ISSUE THREAD

**Issue by gagansk** [CCI-MOC/esi#22]
Production cloud for MOC and Cloud labs. 

DoD:

- Please identify the tasks required for production-ready ESI and associate those tasks to the 'Production ESI Setup' milestone.

**Comment by larsks** [comment]
@gagansk what is the relationship between this issue and #24?

**Comment by gagansk** [comment]
@larsks I am sorry for not phrasing it right. 

#24 is about listing the **features** that should be part of the production ESI environment. @tzumainn will take care of this. 

This issue is related to just the **hardware and other dependencies** required for the production ESI.

**Comment by tzumainn** [comment]
To further clarify, I figured you had a good handle on what needed to be done; https://github.com/CCI-MOC/esi/issues/24 is more about me doing my due diligence and making sure that there aren't any additional gotchas (along the lines of adding OCT switch support).

**Comment by tzumainn** [comment]
https://docs.massopen.cloud/en/latest/clusters/OCT-nodes.html?highlight=oct-3
