### ISSUE TITLE
Wrangle up some MOC "volunteers" to test the ESI Pilot

### ISSUE THREAD

**Issue by tzumainn** [CCI-MOC/esi#231]
Wrangle up some MOC "volunteers" to test the ESI Pilot

**Comment by joachimweyl** [comment]
@naved001 I volunteer for ESI pilot

**Comment by naved001** [comment]
I will also do some testing once this is available.

**Comment by tzumainn** [comment]
I'm splitting this up into smaller tasks based on the MOC tests documented in https://docs.google.com/document/d/1IuqLqN-vxgstG8Nb0gPdxSiIn3tu_yfN1IhhP5KxA_E/edit#

**Comment by joachimweyl** [comment]
@tzumainn can you please link the smaller pieces to this Issues so we can track it as this was part of our current sprint.

**Comment by tzumainn** [comment]
Oh, whoops! Here they are:

https://github.com/CCI-MOC/esi/issues/246
https://github.com/CCI-MOC/esi/issues/245
https://github.com/CCI-MOC/esi/issues/247

**Comment by joachimweyl** [comment]
@naved001 did you want to pull any of those into your sprint?

**Comment by naved001** [comment]
@joachimweyl thanks, I pulled in a couple of those.
