### ISSUE TITLE
Set up SSO for MOC ESI Deployment

### ISSUE THREAD

**Issue by tzumainn** [CCI-MOC/esi#238]

**Comment by tzumainn** [comment]
@naved001 I know I created this card, but do you remember what kind of SSO we wanted to integrate with... ? Or am I imagining you talked about this at some point?

**Comment by naved001** [comment]
I did bring this up because we don't want to be creating local keystone accounts for people to use ESI. @knikolla could you guide us what we would need to do in order to get ESI, which is basically openstack, to use SSO? Thanks!

**Comment by knikolla** [comment]
It depends on what you're using to deploy and manage this OpenStack? Is it manually deployed? Is it using RH Director? 

The upstream guide has the necessary steps, but I'm happy to provide further guidance. https://docs.openstack.org/keystone/latest/admin/federation/configure_federation.html

**Comment by DanNiESh** [comment]
> It depends on what you're using to deploy and manage this OpenStack? Is it manually deployed? Is it using RH Director?
> 
> The upstream guide has the necessary steps, but I'm happy to provide further guidance. https://docs.openstack.org/keystone/latest/admin/federation/configure_federation.html

Hi! We are using OpenStack upstream wallaby release.

**Comment by knikolla** [comment]
Cool. Follow the guide detailing the sections for "Setting up keystone as a service provider" and in particular the ones talking about OpenID Connect. 

Do you want to integrate with the SSO at sso.massopen.cloud or do you want to integrate with something else?

**Comment by knikolla** [comment]
The Devstack OIDC plugin may also be of interest as it has most of the steps scripted out in bash. https://github.com/knikolla/devstack-plugin-oidc

**Comment by DanNiESh** [comment]
https://docs.google.com/document/d/1PRG-uqos9zagLg_yD9a4DSK6cWum9aR7Pnlfser6eJg/edit?usp=sharing

**Comment by knikolla** [comment]
@DanNiESh if I should have access to that document, I don't.

**Comment by DanNiESh** [comment]
> @DanNiESh if I should have access to that document, I don't.

I just sent the invitation. I'm still drafting the doc with questions in red text.

**Comment by tzumainn** [comment]
It sounds like the first ACTUAL step is to figure out who the decision makers are that can decide what the right answer is.

**Comment by tzumainn** [comment]
Okay, it sounds like the goal will be to use MGHPCC coldfront for this. @knikolla do you know if the deprecated MOC OpenStack install also used this ColdFront instance?

**Comment by knikolla** [comment]
@tzumainn the deprecated MOC OpenStack does not use Coldfront. There is a staging coldfront instance running at the NERC that you could probably play around with.

**Comment by tzumainn** [comment]
After a conversation the next steps for the MOC ESI will be to integrate with the MOC keycloak, with potential ColdFront integration on top of that left to a future task. Danni will look into the required updates to the TripleO deployment files, while I will look into the overcloud update process.

**Comment by DanNiESh** [comment]
Related PR: https://github.com/CCI-MOC/esi-pilot/pull/23
I think the next step is to request a client (eg. esi) in the MOC sso environment, and other necessary credentials.
