### ISSUE TITLE
MOC Test: multipath failover

### ISSUE THREAD

**Issue by tzumainn** [CCI-MOC/esi#247]
Test multipath ESI failover

**Comment by naved001** [comment]
I am going to mark it as a medium, because it looks like it's not just about testing multipathing failover rather getting it to work correctly in the first place and I am running into unknown errors with that.

**Comment by tzumainn** [comment]
What kind of issues? Let me know if it's anything I can help with!

**Comment by naved001** [comment]
@tzumainn The summary is when I enabled multipathing the sytem didn't boot and I got into a dracut shell because there were a bunch of I/O errors. Thing that has changed is that in the past we used TGT for providing iSCSI and now we are using LIO (which is what's supported/recommended); so I have to spend some time reading up documentation and figure out what needs to be done. 

I will let you know if there's something I'll need help with.

**Comment by joachimweyl** [comment]
@naved001 as this is medium I would say that [600](https://github.com/CCI-MOC/ops-issues/issues/600) is a higher priority.

**Comment by naved001** [comment]
Once I got multipathing working, it was easy to test for failover. 

This is how your block devices look like, notice the rootfs is on mpathb insteaf of sda or sdb.

```
[root@host-10-21-0-152 ~]# lsblk
NAME        MAJ:MIN RM SIZE RO TYPE  MOUNTPOINT
sda           8:0    0  25G  0 disk
└─mpathb    253:0    0  25G  0 mpath
  └─mpathb1 253:1    0  25G  0 part  /
sdb           8:16   0  25G  0 disk
└─mpathb    253:0    0  25G  0 mpath
  └─mpathb1 253:1    0  25G  0 part  /
[root@host-10-21-0-152 ~]# cat /sys/firmware/ibft/target0/ip-addr
10.21.3.1
[root@host-10-21-0-152 ~]# cat /sys/firmware/ibft/target1/ip-addr
10.21.3.2
```
I then brought down the network interface on one of the iSCSI server, and things continued to work fine as I could still create new files and write to the filesystem. 
```
[root@host-10-21-0-152 ~]# ping 10.21.3.2
PING 10.21.3.2 (10.21.3.2) 56(84) bytes of data.
^C
--- 10.21.3.2 ping statistics ---
2 packets transmitted, 0 received, 100% packet loss, time 999ms
[root@host-10-21-0-152 ~]# echo something > testfile
[root@host-10-21-0-152 ~]# ls
anaconda-ks.cfg  testfile
```

I am going to mark this as done as I tested that multipath failover works as expected. I will open other issues (which I will deal with later) I discovered while working on this.
