### ISSUE TITLE
Volume snapshot when multipathing is in use

### ISSUE THREAD

**Issue by naved001** [CCI-MOC/esi#259]
We have #246 open and that would most likely work when the node isn't using multipathing. A couple of years ago when I snapshotted a node which was booted from multipathed volume, I could not use that volume to boot any other system. It only worked with the original system; I am not sure why but we'll need to investigate this further.

**Comment by naved001** [comment]
I ended up testing this as well and it worked without much work. 

Instead of a volume snapshot I created a separate deep copy of the volume (openstack volume create --volume original_volume --bootable --size <original-size> <copy_volume>), and then the node booted without any problems, though multipathing was not active (i.e. mpath devices weren't there). So I redid the multipathing bits (`multipath -a /dev/sdX` and generate initramfs with /etc/multipath) followed by a reboot and it worked just fine. More details here: https://github.com/CCI-MOC/esi/issues/257#issuecomment-1217169309

**Comment by tzumainn** [comment]
Quick question - should any of this be formally documented anywhere?

**Comment by naved001** [comment]
@tzumainn you are right, we should document this. I can submit a pull request, but to what repo?

**Comment by tzumainn** [comment]
I think to https://github.com/CCI-MOC/esi. If you think it could go on the readthedocs website (https://esi.readthedocs.io/en/latest/index.html) then it could go somewhere in https://github.com/CCI-MOC/esi/tree/master/docs/source/usage ?
