### ISSUE TITLE
Trunk port test

### ISSUE THREAD

**Issue by naved001** [CCI-MOC/esi#270]
Not sure if this is already done, but I wanted to tested this for myself. My goal is to have my node be connected to the storage vlan (as native) so it continues to remain booted, and add a tagged VLAN since I only have one interface to work with.

I have a node, oct4-13 with a single NIC, that I booted from volume. In the process, it created a port for me:
```
| 7c83755e-cff0-4ad5-a739-91161f1507d5 | esi-oct4-13-storage-volume              | 00:0f:53:24:9e:50 | ip_address='10.21.0.152', subnet_id='f4b1f2dc-566e-44ae-8bad-c98f419e54ee' | ACTIVE |
```

The port also has some additional attributes:

```
| extra_dhcp_opts         | ip_version='4', opt_name='tag:ipxe,67', opt_value='http://192.168.24.16:8088/boot.ipxe'                                                                                                  |
|                         | ip_version='4', opt_name='66', opt_value='192.168.24.16'                                                                                                                                 |
|                         | ip_version='4', opt_name='server-ip-address', opt_value='192.168.24.16'                                                                                                                  |
|                         | ip_version='4', opt_name='150', opt_value='192.168.24.16'                                                                                                                                |
|                         | ip_version='4', opt_name='tag:!ipxe,67', opt_value='snponly.efi'                                                                                                                         |
| fixed_ips               | ip_address='10.21.0.152', subnet_id='f4b1f2dc-566e-44ae-8bad-c98f419e54ee'
```

I then created a trunk port 
```
openstack esi trunk create --native-network storage --tagged-networks naved-personal naved-trunk
```

which is called `esi-naved-trunk-naved-personal-sub-port` in the output of `openstack port list` command. This port does not have any `extra_dhcp_opt` set; I guess I should set those but I don't know how to.

Next, I removed my node from the port that was automatically created.
```
openstack esi node network detach oct4-13 esi-oct4-13-storage-volume
```

and then I connected it to the port that I had created:

```
openstack esi node network attach --port esi-naved-trunk-naved-personal-sub-port oct4-13
```

and now my node won't boot because the switchport is shutoff. `openstack port list` reports the port I connected to as being "Down". 

What should I be doing?

**Comment by tzumainn** [comment]
Quick question - what happens if you detach the port and re-attach the storage network? Does the switchport come back up?

**Comment by naved001** [comment]
I did that now and port came back up.

**Comment by tzumainn** [comment]
Oh, I see what happened. You want to attach the main trunk port:

```
openstack esi node network attach --port esi-naved-trunk-storage-trunk-port oct4-13
```

After doing so it looks like the switchport is back up:

```
Te 1/5                            Up     10000 Mbit   Full   213,625
```

**Comment by naved001** [comment]
> esi-naved-trunk-storage-trunk-port

did you create this?

**Comment by naved001** [comment]
looks like it was already there, the trunk port I created was called `naved-personal` which though mapped to `esi-naved-trunk-naved-personal-sub-port`

**Comment by naved001** [comment]
Tested this in #278
