### ISSUE TITLE
Document creating and adding a new network

### ISSUE THREAD

**Issue by naved001** [CCI-MOC/esi#271]
I created a network and tried to attach it to my node which I planned to provision using some external service. However, the switchport configuration was not updated. After some tinkering, @tzumainn pointed out that the ansible driver expects an IP to be assigned to the port. Once a subnet was created for that network, the switchport configuration was applied.

I am opening this issue because this is something worth documenting. I did not create a subnet because it shouldn't really matter to the ESI service as it has little to do with what I do on that network, but apparently it is required so we gotta do it.

**Comment by tzumainn** [comment]
https://github.com/CCI-MOC/esi/pull/277
