### ISSUE TITLE
Install updated esi packages on pilot server

### ISSUE THREAD

**Issue by tzumainn** [CCI-MOC/esi#274]

**Comment by tzumainn** [comment]
@DanNiESh the updated 0.2.0 packages for esi-leap, python-esileapclient, and python-esiclient are now available; they've been tested on the demo server. When you get the chance, can you update/test the MOC ESI deployment (installing the client packages on the undercloud server, I guess)? No immediate rush!

**Comment by DanNiESh** [comment]
> @DanNiESh the updated 0.2.0 packages for esi-leap, python-esileapclient, and python-esiclient are now available; they've been tested on the demo server. When you get the chance, can you update/test the MOC ESI deployment (installing the client packages on the undercloud server, I guess)? No immediate rush!

Sure! Will do.
