### ISSUE TITLE
Cannot connect a node to any network

### ISSUE THREAD

**Issue by naved001** [CCI-MOC/esi#278]
```
[\u@\h \W(<project_name>)]$ metalsmith deploy --resource-class baremetal --image centos-image --network provisioning --ssh-public-key ~/.ssh/id_rsa.pub
+--------------------------------------+-----------+--------------------------------------+----------+--------+-----------------------------+
| UUID                                 | Node Name | Allocation UUID                      | Hostname | State  | IP Addresses                |
+--------------------------------------+-----------+--------------------------------------+----------+--------+-----------------------------+
| 27f4946b-e57e-4a48-8daa-98f2856d4b7c | oct4-13   | eced1bb1-f0c9-499b-a3fa-fc5d59afa497 | oct4-13  | ACTIVE | provisioning=192.168.11.140 |
+--------------------------------------+-----------+--------------------------------------+----------+--------+-----------------------------+
```

And I see that the port metalsmith created is attached:
```
[\u@\h \W(<project_name>)]$ openstack port list |grep 140
| 80bceca7-cc4e-493f-a5e5-0fcff27a1e4f | oct4-13-provisioning                            | 00:0f:53:24:9e:50 | ip_address='192.168.11.140', subnet_id='ddec2b8a-47a1-4e59-9aa3-8186f5d3bc25' | ACTIVE |
```

but the switchport was shutoff after the deployment was complete
```
oct-dell-4#show interfaces switchport tengigabitethernet 1/5
oct-dell-4#show running-config interface tengigabitethernet 1/5
!
interface TenGigabitEthernet 1/5
 no ip address
 shutdown
oct-dell-4#
```

Is there something missing that I should be doing?

**Comment by naved001** [comment]
Attempt to detach looked like it failed, but it went through.
```
[\u@\h \W(<project_name>)]$ openstack esi node network detach oct4-13 oct4-13-provisioning
Detaching node oct4-13 from port oct4-13-provisioning
Gateway Timeout (HTTP 504)
[\u@\h \W(<project_name>)]$ openstack esi node network detach oct4-13 oct4-13-provisioning
Detaching node oct4-13 from port oct4-13-provisioning
Unable to detach VIF 80bceca7-cc4e-493f-a5e5-0fcff27a1e4f from node 27f4946b-e57e-4a48-8daa-98f2856d4b7c because it is not attached to it. (HTTP 400)
```

Then I attempted to add a different port (a trunk port instead, which is what I originally wanted to test).
```
[\u@\h \W(<project_name>)]$ openstack esi node network attach oct4-13 --port esi-naved-created-trunk-naved-personal-sub-port
Attaching port esi-naved-created-trunk-naved-personal-sub-port to node oct4-13
Gateway Timeout (HTTP 504)
[\u@\h \W(<project_name>)]$ openstack esi node network attach oct4-13 --port esi-naved-created-trunk-naved-personal-sub-port
ERROR: Node oct4-13 has no free ports
```
While openstack CLI says it is `ACTIVE`, the switchport configuration was not updated.

```
[\u@\h \W(<project_name>)]$ openstack port list |grep esi-naved-created-trunk-naved-personal-sub-port
| 192ffc2a-4bc9-4513-83dd-fde091490b20 | esi-naved-created-trunk-naved-personal-sub-port | 00:0f:53:24:9e:50 | ip_address='192.168.12.157', subnet_id='95db12c4-50d6-4c1c-9c40-ca924948ca7a' | ACTIVE |
```

Commands that should have affected the switchports took several minutes to complete, I am assuming there are some switch communication failures and I assume that metalsmith wanted to keep the node attached to the provisioning network but the failures are unrelated to metalsmith so I will change the title of this issue.

@DanNiESh Do you have any suggestions about what could be going on here?

**Comment by naved001** [comment]
> I am assuming there are some switch communication failures and I assume that metalsmith wanted to keep the node attached to the provisioning network but the failures are unrelated to metalsmith so I will change the title of this issue.

That being said, the switchports did get configured when the node was being deployed.

**Comment by naved001** [comment]
@tzumainn okay, thanks!

Also it might be worth checking out if we have logs to see what was happening when I got those 504s
```
Gateway Timeout (HTTP 504)
```

**Comment by tzumainn** [comment]
Those are because operations can occasionally take too long due to switch operations and hit the api request timeout. Sam is looking into performance issues that may mitigate the issue a bit; if that doesn't work we may also simply raise the timeout.

**Comment by tzumainn** [comment]
I just finished using metalsmith to provision oct4-13, and things seemed to work as expected; the switch shows:

```
oct-dell-4#show interfaces status | grep 1/5
Te 1/5                            Up     10000 Mbit   Full   623
```

Would it make sense for me to undeploy and for you to try again? This way if something goes wrong I can look into it immediately.

**Comment by naved001** [comment]
> Would it make sense for me to undeploy and for you to try again? This way if something goes wrong I can look into it immediately.

Yes, that would be helpful.

**Comment by naved001** [comment]
I retested things and was successfully able to attach a trunk port to my node. I did get the timeout error message but the switchport was correctly configured.
