### ISSUE TITLE
'openstack esi node network attach' does not work super well with trunks

### ISSUE THREAD

**Issue by tzumainn** [CCI-MOC/esi#281]
The instinct may be to use '--port <trunk name>' which will fail because the trunk name is not a port.

* we should have a better error message when a user uses a non-port name
* we may want to add a '--trunk <trunk name>' option

**Comment by naved001** [comment]
Also, there are 2 ports under a trunk so that may also be confusing for end users (which port to specify). 

```
+---------------------+-------------------------------------------------+----------------------+
| Trunk               | Port                                            | Network              |
+---------------------+-------------------------------------------------+----------------------+
| naved-created-trunk | esi-naved-created-trunk-provisioning-trunk-port | provisioning (623)   |
|                     | esi-naved-created-trunk-naved-personal-sub-port | naved-personal (625) |
+---------------------+-------------------------------------------------+----------------------+
```

**Comment by tzumainn** [comment]
https://github.com/CCI-MOC/python-esiclient/pull/43

@naved001 Danni has added a "--trunk <trunk>" option, which should resolve the confusion.

@DanNiESh Can you also update the ESI read-the-docs documentation?

**Comment by DanNiESh** [comment]
> [CCI-MOC/python-esiclient#43](https://github.com/CCI-MOC/python-esiclient/pull/43)
> 
> @naved001 Danni has added a "--trunk " option, which should resolve the confusion.
> 
> @DanNiESh Can you also update the ESI read-the-docs documentation?

Sure!

**Comment by tzumainn** [comment]
https://github.com/CCI-MOC/esi/pull/299#pullrequestreview-1098212610
