### ISSUE TITLE
Auto-renewal for a let's encrypt certificate

### ISSUE THREAD

**Issue by tzumainn** [CCI-MOC/esi#308]

**Comment by larsks** [comment]
Sure. We just need to set up a CNAME for the appropriate `_acme-challenge` record, like this for `api.ocp-prod.massopen.cloud`:

```
$ dig _acme-challenge.api.ocp-prod.massopen.cloud
_acme-challenge.api.ocp-prod.massopen.cloud. 69 IN CNAME _acme-challenge.api.ocp-prod.acme.massopen.cloud.
```

And then configure whatever ACME client we're using to use the delegated domain.

We probably want to create an IAM user specifically for that purpose (as we've done with e.g. the `ocp-prod-letsencrypt` IAM user).

**Comment by DanNiESh** [comment]
cronjob updated. PR: https://github.com/CCI-MOC/esi-pilot/pull/21
