### ISSUE TITLE
Add documentation clarification to external networks regarding admin tasks

### ISSUE THREAD

**Issue by tzumainn** [CCI-MOC/esi#322]
https://esi.readthedocs.io/en/latest/usage/network_scenarios.html#floating-ips specifies that in order to use floating IPs, the controllers must be configured to be able to access the private network's VLAN. This takes three steps:

* updating the switch to give the controllers access to the vlan
* create a network interface for this vlan on the controllers
* add a route

The first two steps require the private network to be created so that the vlan ID is known; the last step requires the subnet to be created so that the parameters of the route are known.

**Comment by tzumainn** [comment]
@naved001 @larsks Kinda curious if you had thoughts or recommendations about this; is there any way this can be automated somehow (I can't figure it out if so), or is this level of admin involvement a necessary evil? Are there other alternatives that requires less involvement?

**Comment by larsks** [comment]
@tzumainn we can automate anything! :smile: But I think you're asking about automating this *in the context of OpenStack*, and I'll have to think about that a bit.

In the normal course of events, when using Nova to create virtual instances, the process looks like:

1. Create the tenant networks
1. Create a router
1. Connect the router to the tenant networks
1. Connect the router to the floating ip network

I *think* we ought to be able to follow the same process when working with bare metal instances, but I would need to try it out. I would expect Neutron to take care of switch configuration, but perhaps I'm mistaken on that front.

I'll try to do some research on this. I may bug you for access to a running ESI environment.

**Comment by tzumainn** [comment]
@larsks thanks - no rush at all!

The steps you describe for 2-4 are things we do anyway - but the steps I mention in the description seem to me to be prerequisites for all of that, and that's what I'm unsure about automating.

**Comment by tzumainn** [comment]
Looks like this old task is no longer needed.

**Comment by tzumainn** [comment]
Solved by https://github.com/CCI-MOC/ops-issues/issues/1153#issuecomment-1762071173

**Comment by joachimweyl** [comment]
@tzumainn as this was completed this sprint please add a ZH estimate for it.

**Comment by tzumainn** [comment]
Done!
