### ISSUE TITLE
Add new machines to MOC ESI

### ISSUE THREAD

**Issue by tzumainn** [CCI-MOC/esi#331]
Tracked by: https://github.com/CCI-MOC/ops-issues/issues/758

**Comment by DanNiESh** [comment]
Where can we find the nodes information to import them to overcloud?

**Comment by tzumainn** [comment]
I think we'll have to wait until hakan finishes the provisioning, as tracked by the issue linked in the description. After that's done, we should be able to ask him!

**Comment by tzumainn** [comment]
Looks like hakan has handled this, so it's done!
