### ISSUE TITLE
documentation about creating a volume when booting a node from volume.

### ISSUE THREAD

**Issue by naved001** [CCI-MOC/esi#334]
https://esi.readthedocs.io/en/latest/usage/cli.html#volume

Hi @tzumainn Did we document the steps to actually create a volume from some available image as part of "booting a node from volume"?

Thanks!

**Comment by tzumainn** [comment]
Oh whoops - we did not! Can you review this documentation PR?

https://github.com/CCI-MOC/esi/pull/335

**Comment by tzumainn** [comment]
"why yes, the documentation was there all along!"

**Comment by naved001** [comment]
@joachimweyl The documentation was updated to add the necessary step of creating a volume from an image.
