### ISSUE TITLE
Figure out how to update MOC ESI image and redeploy containers

### ISSUE THREAD

**Issue by tzumainn** [CCI-MOC/esi#337]

**Comment by tzumainn** [comment]
@DanNiESh @naved001 Let me know if you have any comments on my proposed testing plan!

I'm probably going to test this out on the MOC ESI sometime (hopefully) soon. The procedure can't be done on the demo server, as that's standalone tripleo. The instructions I'm going to follow are here:

https://docs.openstack.org/project-deploy-guide/tripleo-docs/latest/post_deployment/upgrade/minor_update.html

The only steps that we need to follow are `openstack overcloud update prepare` followed by `openstack overcloud update run`, which can be run against one controller. So the overall steps would be as follows:

* Backup /var/lib/config-date/puppet-generated on controller0
* Run `openstack overcloud update prepare`
* Run `openstack overcloud update run` against controller0
* Run the post-deploy ansible playbooks against controller0 only
* Compare the new config files against the old ones to note any discrepencies (the important ones are Ironic, Neutron, and later Keystone)

Does this sound reasonable? Any other precautions we might be able to take?

**Comment by DanNiESh** [comment]
> 

It might useful to save the screenshot of "podman ps", "ip a" to compare the containers and networks status.

I have a vague memory that I tried to run tripleo update once but somehow it failed.

**Comment by tzumainn** [comment]
That's a really good idea! I'll do that as well.

Do you remember the result of the failure? Was the controller unusable afterwards, or did it just remain in the previous state?

**Comment by tzumainn** [comment]
I tested this against controller2, following these steps:

* ./update.sh
* openstack overcloud external-update run --tags container_image_prepare
* openstack overcloud update run --limit overcloud-controller-2

I ran into a few issues:

* package dependency issues during an update; solved by adding `exclude=container-selinux-2:2.189* pacemaker* corosync*` to /etc/yum.repos.d/CentOS-Stream-AppStream.repo
* after a failed update, you have to run `pcs cluster start` for the update to succeed
* after the update completes, it's possible that the coordination_url in ml2_ansible.ini will no longer be pointed at the master redis instance; if not, you'll have to update this value in ml2_ansible.ini in all three controllers

After the update, it seems as if the configuration files were untouched. However the containers were redeployed, meaning I had to re-apply the manual changes to the neutron container for the nos switch and the trunk port fix.

**Comment by tzumainn** [comment]
Next steps:

* update the neutron dockerfile, and see if a redeploy uses the updated container
* try a redeploy with updated parameters for SSO

**Comment by tzumainn** [comment]
This seems to work with an updated image suffix and running these postinstall playbooks:

   * switch
   * dnsmasq (some diffs in /var/lib/neutron/dhcp)
   * policy
   * ironic_config

In addition, it may be worth double checking the cinder configuration, and the keystone memcache settings as well as `inspect_wait_timeout` and `ramdisk_image_download_source` in ironic.conf.

I'll update esi-custom.yaml one more time tomorrow and try to update controller0 and controller1.

**Comment by tzumainn** [comment]
https://github.com/CCI-MOC/esi-pilot/pull/29
