### ISSUE TITLE
Update MOC ESI with configuration for brocade switch

### ISSUE THREAD

**Issue by tzumainn** [CCI-MOC/esi#338]
This should include files and procedures that this configuration is part of any redeploy

**Comment by joachimweyl** [comment]
is this related to https://github.com/CCI-MOC/ops-issues/issues/777

**Comment by naved001** [comment]
@joachimweyl related, but different.

**Comment by tzumainn** [comment]
@DanNiESh can you point naved to the post-install ansible scripts so he can file a PR to make any changes persistent? Thanks!

**Comment by naved001** [comment]
@tzumainn I have updated `/var/lib/config-data/puppet-generated/neutron/etc/neutron/plugins/ml2/ml2_conf.ini` on all the 3 controllers to include the information about the brocade switch.

I guess the next step is to register a server that uses that switch port on that switch?

**Comment by tzumainn** [comment]
@naved001 correct! There's two-ish steps:

a) 'openstack baremetal node create'; you can see the required information in esi-pilot/bm_inventory.json. I think that file can also be read by some script to create the nodes all at once, but I'm not entirely sure which; @DanNiESh do you know?
b) the script esi-pilot/openstack_commands/node_manage.sh show the next steps - creating the baremetal port and running the requisite ironic commands to perform initial inspection. The big thing here would be to use 'switch2' instead of 'switch1' for the port's switch_info

**Comment by tzumainn** [comment]
Ah, the command to create nodes from a json file is just `openstack baremetal create <json file>`; it might make sense to start a new one for these nodes?

**Comment by naved001** [comment]
@tzumainn Sure, I can create another json file to the new set of nodes.

I noticed there's this file https://github.com/CCI-MOC/esi-pilot/blob/main/instackenv.json which also has similar information about the nodes?

**Comment by tzumainn** [comment]
Ah, instackenv.json is used by the undercloud.

**Comment by naved001** [comment]
@tzumainn 

I followed https://github.com/CCI-MOC/esi-pilot/blob/main/openstack_commands/node_manage.sh and registered my node, and it is in "enroll" state and for that reason I cannot run inspect on it. Am I missing something?

**Comment by DanNiESh** [comment]
> @naved001 correct! There's two-ish steps:
> 
> * 'openstack baremetal node create'; you can see the required information in esi-pilot/bm_inventory.json. I think that file can also be read by some script to create the nodes all at once, but I'm not entirely sure which; @DanNiESh do you know?
Yes.  'openstack baremetal create bm_inventory.json' imports all nodes at once. This command should have been added to node_manage.sh but I forgot it.
> * the script esi-pilot/openstack_commands/node_manage.sh show the next steps - creating the baremetal port and running the requisite ironic commands to perform initial inspection. The big thing here would be to use 'switch2' instead of 'switch1' for the port's switch_info

**Comment by DanNiESh** [comment]
> @DanNiESh can you point naved to the post-install ansible scripts so he can file a PR to make any changes persistent? Thanks!

The related files are: 1) https://github.com/CCI-MOC/esi-pilot/blob/main/ansible-deployment/switch/tasks/main.yaml. This task modifies ansible switch configuration. 
2) https://github.com/CCI-MOC/esi-pilot/blob/main/ml2-ansible-hosts.yaml. However I don't think configuring things in this yaml file will make changes to ansible.ini file on overclouds. So actually only 1) takes effect to modify ini file.
