### ISSUE TITLE
Configure overcloud hosts to reach management and ipmi of MOC switches/servers

### ISSUE THREAD

**Issue by naved001** [CCI-MOC/esi#339]
Since that is a physically separate network we will need to do some routing.

**Comment by naved001** [comment]
I added this route to all 3 controllers manually. 

```
sudo ip route add 10.0.0.0/19 via 129.10.5.105
```

it's not persistent yet, but this route needs to part of the configuration. This gives the controllers access to the IPMI of the servers and switch management.


On the router itself (129.10.5.105), I needed to add
```
iptables -A FORWARD -s <controller-ip> -d 10.0.0.0/19 -j ACCEPT
```
but that only made the traffic for the server's IPMI controller work, and not the switches and that's because the switches don't have a default gateway (and I couldn't figure out how to configure one), so another rule was added for masquerading the source IP so the switch's response could be returned. 

```
iptables -t nat -A POSTROUTING -s <controller-ip> -o eth1 -j MASQUERADE
```

**Comment by tzumainn** [comment]
@DanNiESh is route configuration part of the post-install ansible scripts?

**Comment by DanNiESh** [comment]
> 

We have provisioning network route configuration: https://github.com/CCI-MOC/esi-pilot/blob/351d91c4640d07382313e57ca9cd3f5ddaeb2a71/openstack_commands/network.sh#L40. We can add IPMI routing in network.sh script.

**Comment by tzumainn** [comment]
What about something that runs 'ip route' commands on each controller? I had the impression that one of the ansible playbooks did that, or am I wrong?

**Comment by DanNiESh** [comment]
> What about something that runs 'ip route' commands on each controller? I had the impression that one of the ansible playbooks did that, or am I wrong?

Ah, it's here: https://github.com/CCI-MOC/esi-pilot/blob/351d91c4640d07382313e57ca9cd3f5ddaeb2a71/ansible-deployment/node_deploy/tasks/main.yaml
