### ISSUE TITLE
Determine alternate path for owner changes

### ISSUE THREAD

**Issue by tzumainn** [CCI-MOC/esi#34]
Owner changes are dangerous; allow for future permissions are hard, and there are all sorts of complex use cases that may result in unexpected behavior.

This requirement may be fulfilled by an alternative workflow, such as:

* Owner A offers up their node to Owner B's project tree
* We allow for subleases

**Comment by hpdempsey** [comment]
NERC and CloudLab have both confirmed that we do not need to change the owner of a node for ESI/LEAP implementation.  The administrators of CloudLab and the adminstrators from Harvard or BU IT (for NERC) approved the proposal that an admin from their organization can lease a bare metal machine on behalf of their users, and they can then (at their option) offer subleases to their users using ESI.  I revised the use cases to state this already (https://docs.google.com/document/d/12G4w9Os2bIUbL8ZadxCYVUSU0ZOo12_YW-6dAaWM0DA/edit?usp=sharing).  I think the implementation doc needs a change, which I entered as a comment ( https://docs.google.com/document/d/1CL9hvYWLxYDH6To92gIDnLfPGn3UIcaxOWj4lfDmLAA/edit?usp=sharing) Please review.  If acceptable,  we should be able to close this issue and remove the owner change code.  This will require revisions to the test plans as well.

**Comment by tzumainn** [comment]
Great! I'll:

* update the implemetation doc
* remove the owner change code

The test plans actually don't cover owner changes right now (I asked elliot and sam to ignore them for now knowing that they were likely to go away). I'll drop a note in the testing plan task to do another pass over test cases, specifically checking for the new workflows as described in the soon-to-be-updated implementation doc.

**Comment by tzumainn** [comment]
Implementation doc updated (https://docs.google.com/document/d/1CL9hvYWLxYDH6To92gIDnLfPGn3UIcaxOWj4lfDmLAA/edit#)

I'll move this to "under review" after I create the PR to remove the owner change code.

**Comment by tzumainn** [comment]
https://github.com/CCI-MOC/esi-leap/pull/87
https://github.com/CCI-MOC/python-esileapclient/pull/27
