### ISSUE TITLE
Register some HIL servers into ESI

### ISSUE THREAD

**Issue by naved001** [CCI-MOC/esi#340]
This includes some basic network provisioning of the said servers and producing some documentation along the way.

**Comment by naved001** [comment]
I used a script to get info out of HIL and then register a server into ESI. It lives here: https://github.com/naved001/hil-to-esi/blob/main/main.py

**Comment by naved001** [comment]
a sample json blob that I used to register a HIL server with 2 NICs into ESI, looks like this:

```
{
  "nodes": [
    {
      "name": "neu-19-38",
      "properties": {
        "capabilities": "iscsi_boot:True"
      },
      "resource_class": "baremetal",
      "driver": "ipmi",
      "driver_info": {
        "deploy_kernel": "UUID of deploy_kernel for the image",
        "deploy_ramdisk": "UUID of the deploy_ramdisk of the image",
        "ipmi_username": "username",
        "ipmi_password": "password",
        "ipmi_address": "10.0.19.38"
      },
      "ports": [
        {
          "address": "d4:ae:52:9a:b7:80",
          "physical_network": "datacentre",
          "local_link_connection": {
            "switch_info": "brocade-15-42",
            "port_id": "TenGigabitEthernet 7/0/35",
            "switch_id": "50:eb:1a:61:5d:6a"
          }
        },
        {
          "address": "d4:ae:52:9a:b7:82",
          "physical_network": "datacentre",
          "local_link_connection": {
            "switch_info": "brocade-15-42",
            "port_id": "TenGigabitEthernet 7/0/36",
            "switch_id": "50:eb:1a:61:5d:6a"
          }
        }
      ]
    }
  ]
}
```
You can get the Ramdisk UUID with `openstack image show centos-8-deploy-ramdisk  -f value -c id` for an image names centos-8-deploy-ramdisk. Similarly, the Kernel UUID can be obtained with `openstack image show centos-8-deploy-kernel -f value -c id`. 

Part of `driver_info` is the `ipmi_terminal_port`, which has to be unique i.e. no other node should have that so it can either be manually added later on using the command line to set it, or just increment the port by 1.

**Comment by naved001** [comment]
once the node is enrolled

`openstack baremetal node manage <node-name>`
`openstack baremetal node inspect <node-name>`

**Comment by naved001** [comment]
once the node has been successfully inspected, you'll see harware information about the node if you run `openstack baremetal ndoe show <node-name>`

**Comment by joachimweyl** [comment]
A good set of HIL nodes to start with would be the 12 that are not in use bu-23-101, neu-03-10, neu-03-12, neu-05-12, neu-15-11, neu-17-25, neu-17-34, neu-17-35, neu-17-38, neu-19-34, neu-19-38, neu-19-7.

**Comment by naved001** [comment]
I am going to close this issue as I have added the nodes that could have been added without requiring any hardware changes/fixes.
