### ISSUE TITLE
Work with Dan Radez to get network-runner code merged

### ISSUE THREAD

**Issue by tzumainn** [CCI-MOC/esi#344]

**Comment by joachimweyl** [comment]
code merged. [PR here](https://github.com/ansible-network/network-runner/pull/73).

**Comment by tzumainn** [comment]
I don't think the code actually merged due to a merge conflict.

**Comment by radez** [comment]
Agree, the merge failed. Probably should reopen #73 and rebase it.

**Comment by naved001** [comment]
I do see the code though and the commit. 

https://github.com/ansible-network/network-runner/tree/devel/etc/ansible/roles/network-runner/providers/nos

https://github.com/ansible-network/network-runner/commits/devel

Not sure what's going on
