### ISSUE TITLE
Follow up on TPM bug report

### ISSUE THREAD

**Issue by tzumainn** [CCI-MOC/esi#345]

**Comment by tzumainn** [comment]
@DanNiESh can you link the bug report you filed here? Thanks!

**Comment by DanNiESh** [comment]
Bug report: https://docs.google.com/document/d/1GN9Us4-rMP2Q0nxWaknWb_qEtg0OHBwxwT05JNFzSJ0/edit?usp=sharing

**Comment by joachimweyl** [comment]
no longer needed
