### ISSUE TITLE
What are NERC requirements for ESI?

### ISSUE THREAD

**Issue by tzumainn** [CCI-MOC/esi#348]
This document should address immediate NERC concerns, as well as speculate about future directions of interest to NERC.

**Comment by knikolla** [comment]
@msdisme @tzumainn could you please provide a link to the document these are being worked on?

**Comment by knikolla** [comment]
@gagansk ^

**Comment by joachimweyl** [comment]
@gagansk please when you have a moment please update the estimate on this. @tzumainn and I set it at 8 to start but that is just a placeholder.

**Comment by joachimweyl** [comment]
@gagansk pushing this out to the next sprint as I have seen no updates on this.

**Comment by joachimweyl** [comment]
@gagansk is this still in your queue or do we need to find a new writer for this?

**Comment by gagansk** [comment]
I think this slipped from my tasks. I am not working on it. And assuming ESI is already operational in NERC, we can close this. @tzumainn do we still need this?

**Comment by tzumainn** [comment]
Thinking about it, if there are other NERC/ESI related tasks, perhaps any additional requirements would just spin naturally out of those?

**Comment by joachimweyl** [comment]
The point of this was to have someone familiar with ESI talk to someone from the NERC team to tease out the current fears and requirements NERC has around using ESI. Then have ESI team review the document to find out which of the concerns they can answer right away and which ones we would need to test.
If Gagan is unable to do this who should we get from the ESI team to work on this?
Yes if there are already issues out there those would be a good idea to put into the document as concerns that are being answered.

**Comment by tzumainn** [comment]
I guess my feeling is that the work that Justin and Steve have done integrating ESI nodes into their OpenShift and OpenStack have exposed a lot of issues that we've worked on (for example, floating IPs only exposing certain ports). I don't know if there is a level of requirements higher than that right now - big picture items and the like? If so, then my gut feel is that level of discussion may require participation from more than software engineers.

**Comment by joachimweyl** [comment]
That makes sense. Let's consider this something that would have been nice to have prior to starting work but now that the work has started we have gathered what we needed in the individual issues.
