### ISSUE TITLE
Compare switch speeds

### ISSUE THREAD

**Issue by tzumainn** [CCI-MOC/esi#349]

**Comment by tzumainn** [comment]
Brocade switch:

* 2023-01-26 19:02:15.155 7 INFO ironic.conductor.task_manager [req-435885a7-fed0-49ab-afff-3b19d82f86a7 a2eb20a1bf94440e807c903113c71d12 ce54871194264a1dafd508058c0b8614 - default \
<tzumainn> default] Node 2d93132b-b97e-4e90-933d-6604103d11a3 moved to provision state "inspecting" from state "manageable"; target provision state is "manageable"
* 2023-01-26 19:14:06.499 30 INFO networking_ansible.ml2.mech_driver [req-0181e655-ff04-4399-aec5-e2d1103e852c 7458ddc16b6e4a98b9c7c98f2819a764 0766c357f95e491e8f92df9de75d1fa5 - default default] Port d9bb0d38-a299-42e9-9172-8a0e1747c781 has been plugged into switch port TenGigabitEthernet 3/0/19 on device brocade-15-42

12 minutes

**Comment by tzumainn** [comment]
@naved001 here's some data, in case you're curious!

**Comment by naved001** [comment]
whoa, really need to look into the community plugin for nos and see if there's room for optimization there.

**Comment by tzumainn** [comment]
Brocade switch with changes from https://github.com/ansible-network/network-runner/compare/devel...naved001:network-runner:vdx-nos/improve-performance:

* 2023-01-27 17:08:25.211 7 INFO ironic.conductor.task_manager [req-08985e34-ec8c-4ef1-8d0e-b5997792bf94 a2eb20a1bf94440e807c903113c71d12 ce54871194264a1dafd508058c0b8614 - default \
default] Node 2d93132b-b97e-4e90-933d-6604103d11a3 moved to provision state "inspecting" from state "manageable"; target provision state is "manageable"
* 2023-01-27 17:14:55.835 27 INFO networking_ansible.ml2.mech_driver [req-4a8777ff-93d3-446c-87af-97862f5423bb 7458ddc16b6e4a98b9c7c98f2819a764 0766c357f95e491e8f92df9de75d1fa5 - default default] Port ba9c556a-d196-48f4-b892-1f0783da6727 has been plugged into switch port TenGigabitEthernet 3/0/19 on device brocade-15-42

6 minutes! Definitely faster.
