### ISSUE TITLE
Investigate occasional loss of external network connectivity for controller0 in MOC ESI

### ISSUE THREAD

**Issue by tzumainn** [CCI-MOC/esi#354]

**Comment by tzumainn** [comment]
Danni has spotted the related issue: https://github.com/CCI-MOC/esi/issues/204

Naved confirms it's the problem:

<naved001> from controller1 I pinged the IP that I think is assigned to two hosts., After a bunch of pings (6-7), I then look at the arp table and see what mac address it resolved to.
<naved001> if there's more than 1, then that's a problem
<naved001> [heat-admin@overcloud-controller-1 ~]$ arp -n |grep 129.10.5.141
<naved001> 129.10.5.141             ether   00:0f:53:2c:a2:f1   C                     enp65s0f1np1
<naved001> 129.10.5.141             ether   b8:ca:3a:6c:3c:68   C                     eno1

**Comment by naved001** [comment]
for posterity:

```
[heat-admin@overcloud-controller-1 ~]$ ping 129.10.5.141^C
[heat-admin@overcloud-controller-1 ~]$ arp -n |grep 129.10.5.141
129.10.5.141             ether   00:0f:53:2c:a2:f1   C                     enp65s0f1np1
129.10.5.141             ether   b8:ca:3a:6c:3c:68   C                     eno1
```
both interface belong to the same host, though I don't see an IP assigned to eno1 so not sure why it was responding.

**Comment by tzumainn** [comment]
Bringing down eno1 does not seem to affect operation and allows controller0 to maintain a connection to the external internet; however the arp test still shows two entries. Hakan will take a look at the switch later today.

<naved001> eno1 is a 1G interface that shouldn't have beeen configured at all. The only 10G interfaces that should/can be configured are `enp3s0f0np0` and `enp3s0f1np1`

**Comment by tzumainn** [comment]
Hakan has shut off the switchport for eno1, which appears to have resolved the issue. Thanks to all!
