### ISSUE TITLE
Unable to ping one node's IPMI address from 2 out of 3 controllers

### ISSUE THREAD

**Issue by tzumainn** [CCI-MOC/esi#357]
oct4-cha3-1b is currently stuck in enroll, and cannot be moved to manageable. The cause is usually an inability for Ironic to use IPMI to control the machine's power state.

The node's IPMI IP is 10.2.4.132. I can ping this address from controller0, but not from controller1 or controller2.

Weirdly, I can ping oct4-cha3-1a's IPMI (10.2.4.131) from all three controllers. Any idea what might be causing this issue?

**Comment by hakasapl** [comment]
That is very strange. When things like this happen I usually attribute it to some conflict on the network. ie. two devices have the same mac or two devices have the same IP. In this case I'm seeing no signs of that in various arp tables I've checked.

Is there a host in OCT4 @naved001 that has an extra unused port that is attached to the switchport? I'd like to packet capture a port mirror from the switch to get more info but it requires an additional interface to tcpdump on.

**Comment by naved001** [comment]
@hakasapl I think the undercloud host (esi-undercloud.massopen.cloud) that has a spare NIC which isn't used (enp3s0f1np1).

Confirm with @tzumainn  if it's okay to use the other NIC on that host for port mirroring purposes.

**Comment by tzumainn** [comment]
I think that's used by the undercloud to connect to the control plane, so I'd avoid that.

A while back I provisioned an oct machine; you can ssh into it from the undercloud by running `ssh centos@128.31.20.84`. I think eth0 is unsued there. Would that work?

**Comment by joachimweyl** [comment]
@hakasapl what are the next steps on this issue?

**Comment by hakasapl** [comment]
When I am at MGHPCC this week I will install a cable on OCT4-7 which I will use to run a port mirror on the switch and diagnose further.

**Comment by joachimweyl** [comment]
@hakasapl what was the outcome of your testing last week when you were at MGHPCC?

**Comment by hakasapl** [comment]
The network has changed a good amount since we were talking about this. Is this still an issue? If so it may not be worth trying to fix unless it also comes up in the new ESI deployment.

**Comment by tzumainn** [comment]
I just double checked, and this is no longer an issue; closing.
