### ISSUE TITLE
Add a monitoring system check for validity of the MOC ESI certificate

### ISSUE THREAD

**Issue by tzumainn** [CCI-MOC/esi#358]

**Comment by naved001** [comment]
I have added a check in [our monitoring system](https://zabbix.massopen.cloud/history.php?action=showvalues&itemids[]=168221) to send an alert when the certificate validity is less than 25 days

![image](https://user-images.githubusercontent.com/20113064/217317966-67aa2361-478a-4208-81fa-ed8621550399.png)

**Comment by tzumainn** [comment]
Awesome, thanks!
