### ISSUE TITLE
Talk to HIL/BMI researcher regarding expected use of ESI, and create documentation reflecting that

### ISSUE THREAD

**Issue by tzumainn** [CCI-MOC/esi#363]

**Comment by naved001** [comment]
@tzumainn looks like we may not need to provide any images for the researchers at all as they will end up using their some of their own provisioning system. 

I guess for our own testing we could use the centos8 images that's already there.

**Comment by tzumainn** [comment]
Yep, we've been doing that - I'll close the image card then!

**Comment by knikolla** [comment]
I think it's of real value to have some structured training for the grad students and the rest of the team about using ESI. If that is something we want to do, it needs to be worked out how to structure and organize it.

**Comment by tzumainn** [comment]
Yep - I think we can only do that well if we get a sense of what the expectations are from the grad students, though. If we know their typical workflow, then we can tailor our documentation for that.

**Comment by tzumainn** [comment]
@knikolla I should have asked this yesterday, but do you know any grad student we might be able to get in contact with regarding the workflow of how they use HIL/BMI? Or is that something you guys would already know?

**Comment by tzumainn** [comment]
Closing this because we will have tasks to follow up with individual researchers.
