### ISSUE TITLE
Fork network-runner and ansible-networking

### ISSUE THREAD

**Issue by tzumainn** [CCI-MOC/esi#392]
* fork to CCI-MOC
* apply changes
* update custom dockerfiles

**Comment by DanNiESh** [comment]
fork repos to CCI-MOC: https://github.com/CCI-MOC/networking-ansible/tree/esi_networking_ansible (branch from master), https://github.com/CCI-MOC/network-runner/tree/esi_network_runner (branch from tag 0.3.6)
update custom dockerfile: https://github.com/CCI-MOC/esi-pilot/pull/35
