### ISSUE TITLE
Can we automatically disable the unused NICs in the nodes?

### ISSUE THREAD

**Issue by tzumainn** [CCI-MOC/esi#394]
Some nodes will provision fine, but subsequently get stuck in cleaning. That's because when initially provisioning, the boot order will go "unused NIC" -> "Hard drive" -> "in-use NIC"; if there's nothing on the hard drive, then we correctly reach the "in-use NIC". However once that provisioning occurs, subsequent PXE boots will start with the unused NIC, fail, and then default to the hard drive.

**Comment by joachimweyl** [comment]
@tzumainn as we determined this is a higher priority please decide if it should be in the next sprint. if so please add an estimate and assign it to somebody.

**Comment by tzumainn** [comment]
Is it possible to discuss first during sprint planning? Depending on what people say I could see this going in a bunch of different directions.

**Comment by joachimweyl** [comment]
@tzumainn I see this is part of the current sprint but has nobody assigned to it, can you assign this to somebody?

**Comment by tzumainn** [comment]
Let me move it out of the sprint backlog, and it can be discussed at the next grooming meeting?

**Comment by hakasapl** [comment]
This doesn't appear to be possible. Techsquare did this manually for the nodes that needed it
