### ISSUE TITLE
Running out of private network vlans

### ISSUE THREAD

**Issue by tzumainn** [CCI-MOC/esi#395]
VLANs 621-630 are allocated, and are all being used now.

**Comment by naved001** [comment]
This is what could be used:

351 to 499
520 to 630

@hakasapl Does this sound okay? This is a subset of VLANs from what was allocated to HIL so I think there should be no conflict.

kzn-hil and kumo-hil are using VLANS from 250 to 350 and 500 to 519.

**Comment by hakasapl** [comment]
@naved001 The only conflict I see is VLAN 623 in that range, marged as "ESI Inspection and provisioning network". Everything else looks good to me

**Comment by naved001** [comment]
@hakasapl sounds good. right, 623 is already in use by ESI. 

@tzumainn We can update the VLAN range to what's in my previous comment.
