### ISSUE TITLE
disable internal SD on oct4-cha machines

### ISSUE THREAD

**Issue by tzumainn** [CCI-MOC/esi#396]
Derek used metalsmith to provision on a few oct4-cha-* machines; the OS installed on the SD, but the boot sequence only tried the HDs.

**Comment by tzumainn** [comment]
Running ``openstack baremetal node set oct4-cha4-1a --property root_device='{"hctl": "1:0:0:0"}'`` works; I'll update the oct4-cha4 nodes and re-run inspection; and update the inventory files.

**Comment by tzumainn** [comment]
The better hint turns out to be

```
openstack baremetal node set <NODE> --property root_device='{"size": ">= 50"}'
```

**Comment by tzumainn** [comment]
@hakasapl I just realized the oct4-cha* inventories aren't checked into esi-pilot; no rush, but you may want to submit a PR for that at some point, and add in the extra property mentioned above.

**Comment by hakasapl** [comment]
Sure, I'll take care of that

**Comment by tzumainn** [comment]
Resolved by https://github.com/CCI-MOC/esi-pilot/pull/36 - thanks!
