### ISSUE TITLE
Engineer and document an IPMI proxy solution for ESI

### ISSUE THREAD

**Issue by tzumainn** [CCI-MOC/esi#402]

**Comment by tzumainn** [comment]
@samuel-zuk I think the first step is simply to fork the code!

**Comment by samuel-zuk** [comment]
https://github.com/samuel-zuk/virtualbmc Success! I indeed couldn't fork to CCI-MOC but I was successful in forking to my personal account.

**Comment by tzumainn** [comment]
What steps did you take to fork the code? Danni or I should be able to fork it to CCI-MOC

**Comment by samuel-zuk** [comment]
> What steps did you take to fork the code? Danni or I should be able to fork it to CCI-MOC

@tzumainn I followed these instructions: https://docs.github.com/en/migrations/importing-source-code/using-github-importer/importing-a-repository-with-github-importer using this clone URL: https://opendev.org/openstack/virtualbmc.git. I believe anyone with permissions to create repositories should then be able to select CCI-MOC as the account to fork the repo to.

**Comment by tzumainn** [comment]
Thanks! https://github.com/CCI-MOC/virtualbmc is up now; I'll let you know when my stuff is branched in there.

**Comment by tzumainn** [comment]
Okay, https://github.com/tzumainn/virtualbmc/tree/tzumainn-hack has my hacked code, and https://github.com/CCI-MOC/virtualbmc/pull/1 updates the README to explain how to use it (it's pretty much the same other than the install). If you could review the README PR, I can merge it in and then send it to the OKD folks for early tech preview.

**Comment by tzumainn** [comment]
@samuel-zuk thinking about it: I ripped out the vm code and just shoved ironic code in its place. If there's a way to keep both, you could probably contribute the solution back to the original code base.

**Comment by joachimweyl** [comment]
no longer needed.
