### ISSUE TITLE
Add "purpose" field to leases

### ISSUE THREAD

**Issue by tzumainn** [CCI-MOC/esi#403]
**Description of the task -** 

The 'purpose' field will be added to ESI-Leap and the CLI to be included as an optional field when creating a lease. The purpose field will allow users to provide a description of what the leased node will be used for, which will help with automation tasks, such as adding the node to an OpenShift cluster. Additionally, the purpose field will be used in notifications and scripts to determine the correct automation based on the intended use of the leased node.

**Comment by skanthed** [comment]
The 'purpose' field will be added to ESI-Leap and the CLI to be included as an optional field when creating a lease. The purpose field will allow users to provide a description of what the leased node will be used for, which will help with automation tasks, such as adding the node to an OpenShift cluster. Additionally, the purpose field will be used in notifications and scripts to determine the correct automation based on the intended use of the leased node.

**Comment by skanthed** [comment]
Pull request for CLI -  
https://github.com/CCI-MOC/python-esileapclient/pull/48
