### ISSUE TITLE
Add ubuntu image to MOC ESI

### ISSUE THREAD

**Issue by tzumainn** [CCI-MOC/esi#404]
The existing ubuntu image does not add ssh keys to the ubuntu user when using metalsmith

**Comment by tzumainn** [comment]
I've tried a variety of ubuntu image builds using diskimage-builder, and all of them have the same result: ssh keys aren't added. I don't know if there's some fundamental incompatibility; the solution may be to have users create their own ubuntu images.

@DanNiESh do you remember any weird little details from when you created your ubuntu image that might be relevant here?

@naved001 did you ever provide ubuntu images to HIL/BMI users? If so, how did you handle access?

**Comment by DanNiESh** [comment]
Yeah, I remember i can only use console login. I tried to configure ssh login with password in sshd_config, but that didn't work.

**Comment by naved001** [comment]
> did you ever provide ubuntu images to HIL/BMI users? If so, how did you handle access?

Yes, but it was all basically a manual process. There are no images that are public i.e. available to all BMI projects, instead each project required its own OS image(s). So when a new project was created in BMI I would clone an image for the new project and insert the ssh key in that image, I used a script to help automate it, but this was still all outside the scope of BMI.

**Comment by tzumainn** [comment]
Okay! Well, I know how to inject a key into a custom image. In any case, the ukl folks said that the fedora image is working for them, so there's no longer a pressing need for an ubuntu image. Closing this for now.

**Comment by tzumainn** [comment]
Lars noticed missing files, and that led to the conclusion that disk-image-create should be run with `export DIB_CLOUD_INIT_DATASOURCE="NoCloud, ConfigDrive, OpenStack, Ec2"`. I'll try/test this now!

**Comment by tzumainn** [comment]
The newly created ubuntu image works with ssh keys! Thanks @larsks
