### ISSUE TITLE
Ensure `openstack esi node network attach --network <network> <node>` has a more informational error message

### ISSUE THREAD

**Issue by tzumainn** [CCI-MOC/esi#408]
From Emmanuel:

"I had accidentally entered the wrong network number 'openstack esi node network attach --network 413 oct4-06' , and the error message is not very explicit: 'NoneType' object has no attribute 'name'.  Probably should catch the invalid network name and return a more informative error message."

**Comment by skanthed** [comment]
PR- https://github.com/CCI-MOC/python-esiclient/pull/53
