### ISSUE TITLE
Create initial Phase 1 functional testing plan

### ISSUE THREAD

**Issue by tzumainn** [CCI-MOC/esi#41]
Although our code has unit tests, some functional tests would be good as well. Defining these tests is the first step.

**Comment by tzumainn** [comment]
https://docs.google.com/spreadsheets/d/1nj0NWIIuZCYKnvtWMGtoCaJqqvCIIEhajXtyUCNfDQY/edit#gid=0

**Comment by betaredex** [comment]
Documented all the tests I've written in the spreadsheet
