### ISSUE TITLE
Research ESI Performance Project requirements

### ISSUE THREAD

**Issue by tzumainn** [CCI-MOC/esi#415]
https://docs.google.com/document/d/19NILExZ9y4VuQtHmDNqj6yeevFmvf68nxhw5r2CblfM/edit

First step will be to break this up into smaller bits!

**Comment by aayushi363** [comment]
Added some steps in the document to follow in order to proceed with this Performance project. Open for comments.

**Comment by tzumainn** [comment]
Thanks, this is a good start! One thing that's missing is a more detailed breakdown of the scenarios that should be tested. Do you have a sense of that yet? If not, we can talk and work that out. Either way, it's something that we're going to want to add to the document.

**Comment by aayushi363** [comment]
I have added detailed breakdown of the scenarios that should be tested categorized as per the ESI code base components.
