### ISSUE TITLE
Set up additional ESI dev environment?

### ISSUE THREAD

**Issue by tzumainn** [CCI-MOC/esi#418]
Looks like our current demo server will go away soon-ish!

Useful links:

- https://docs.openstack.org/tripleo-docs/latest/
- https://github.com/CCI-MOC/esi-sandbox

For now, maybe use one of the ESI nodes controlled by demo server and try and install OpenStack/ESI there.

**Comment by tzumainn** [comment]
@naved001 I think you mentioned that the demo server might go away at some point; is there a replacement machine we can use?

**Comment by naved001** [comment]
@tzumainn We are working on allocating machines to dedicate to an ESI development cluster.

**Comment by joachimweyl** [comment]
@tzumainn please provision one of the FC830s from the Research rack.

**Comment by tzumainn** [comment]
MOC-R4PAC21U21-S3 is provisioned. @skanthed, can you send me your public key?

**Comment by joachimweyl** [comment]
@tzumainn does MOC-R4PAC21U21-S3 resolve this issue or do we need more?

**Comment by joachimweyl** [comment]
@skanthed when you get back I would love to work on this with you to see if we can break this into multiple issues, maybe even create an epic for this issue itself.

**Comment by tzumainn** [comment]
Closing for now, since we will have a staging/dev environment after the new ESI is ready to go
