### ISSUE TITLE
Figure out how ESI pricing might work

### ISSUE THREAD

**Issue by tzumainn** [CCI-MOC/esi#423]
Pricing based on

* leased nodes
* VLAN used
* Pricing tied to potential SU - eg. an FC830 costs more then an fc430

**Comment by msdisme** [comment]
Pricing based on potential SU's?

**Comment by msdisme** [comment]
Confirmed with Monday Strategy meeting - associate costs with SU's - eg. FC430 less expensive then FC830

**Comment by joachimweyl** [comment]
replaced by https://github.com/CCI-MOC/ops-issues/issues/1271
