### ISSUE TITLE
Update `esi node network detach` to make port optional if node only has one network interface

### ISSUE THREAD

**Issue by tzumainn** [CCI-MOC/esi#427]
Right now, the port is required even if there's only one baremetal port. If there's only one baremetal port, then we can assume it's that one; otherwise, this command can throw an error and some informational text

**Comment by skanthed** [comment]
PR - https://github.com/CCI-MOC/python-esiclient/pull/55

**Comment by tzumainn** [comment]
PR merged! @skanthed can you also update https://github.com/CCI-MOC/esi/tree/master/docs/source? Search for all instances of `openstack esi node network detach` and update the calls to the new CLI. Thanks!

**Comment by skanthed** [comment]
PR for documentation update - https://github.com/CCI-MOC/esi/pull/452

**Comment by skanthed** [comment]
PR's Merged!
