### ISSUE TITLE
Develop plan for creating sdk for esi (similar to openstacksdk)

### ISSUE THREAD

**Issue by tzumainn** [CCI-MOC/esi#429]
This would make developing integration scripts a LOT easier

**Comment by DanNiESh** [comment]
https://docs.google.com/document/d/1rXgN8KtrammwgSaGx7khIsh78B9iqDrxsQeY1GhTWG4/edit?usp=sharing

**Comment by tzumainn** [comment]
Danni has broken this up into several smaller tasks.
