### ISSUE TITLE
Figure out how to pass UUID from Keylime Agent to Ironic

### ISSUE THREAD

**Issue by tzumainn** [CCI-MOC/esi#45]
The UUID of the Keylime Agent has to be passed via heartbeat to the Ironic controller and saved via instance_info

**Comment by DanNiESh** [comment]
After talking with Julia, we decided to build an attestation extension in ipa to collect keylime agent info. Accordingly, we need to implement a function in ironic's agent_client to make request to ipa's rest API and update the node with keylime info.

**Comment by ljmcgann** [comment]
We originally were going to use image building to configure the keylime_agent_port, retrieve the keylime_agent_ip from the heartbeat, and had to figure out how to pass the keylime_agent_uuid. Now we have decided that an IPA extension which passes all three of these things at once is the simplest option available to us.

I have written but need to test and debug some code in the Ironic driver creating a new RPC for the controller.

**Comment by DanNiESh** [comment]
Ironic is able to grab keylime info from ipa attestation extension. Security interface runs keylime tenant command to start attestation. But the verifier can't reach out to the node. We are still looking into this issue.
