### ISSUE TITLE
Define requirements for new MOC ESI controllers

### ISSUE THREAD

**Issue by tzumainn** [CCI-MOC/esi#457]

**Comment by tzumainn** [comment]
@naved001 I've started a document at https://docs.google.com/document/d/1pJfL_OTZT0LjxoClYKU8Vvih8YOr0e81-3RhiTjlqaE/edit to list out the requirements; there are almost definitely aspects that I've forgotten about, so if anything comes to mind let me know!

@DanNiESh as the original MOC ESI installer, can you also add in anything I've forgotten?

**Comment by naved001** [comment]
This PR applied the necessary switchport changes: https://github.com/CCI-MOC/ansible-switches/pull/30 for the overcloud nodes. I will also configure the undercloud soon once I know the switchports.

After that I will allocate some IP addresses and some DNS config.

**Comment by joachimweyl** [comment]
@naved001 how did configuing the undercloud and allocating IP addresses go?

**Comment by naved001** [comment]
I configured the overclouds, but got sidetracked and didn't configure the undercloud (the switchports were not known at that time).

**Comment by naved001** [comment]
The undercloud now has 2 interfaces.

Interface for ESI provisioning network:

```
Name: GigabitEthernet 1/12
802.1QTagged: False
Vlan membership:
Q       Vlans
U       214
```

Everything else:

```
Name: GigabitEthernet 1/11
802.1QTagged: Hybrid
Vlan membership:
Q       Vlans
U       127
T       207,911

Native VlanId:    127.
```

**Comment by naved001** [comment]
I have allocated the IPs to be used for the new deployment here: https://github.com/CCI-MOC/documentation/pull/131
