### ISSUE TITLE
Make console show display the console instead of configuration

### ISSUE THREAD

**Issue by khers** [CCI-MOC/esi#458]
The console display command would be much more useful if it actually displayed the console rather than giving output that can be parsed to use as input to `socat` 

Currently, when I run `openstack baremetal console show oct4-09` I get the following output:

```
+-----------------+-----------------------------------------------------+
| Field           | Value                                               |
+-----------------+-----------------------------------------------------+
| console_enabled | True                                                |
| console_info    | {'type': 'socat', 'url': 'tcp://129.10.5.143:8026'} |
+-----------------+-----------------------------------------------------+
```
Which then needs to be translated to an socat invocation like `socat TCP4:129.10.5.143:8026 -`

It would be nicer if this openstack command simply started following the console for the requested machine.

**Comment by tzumainn** [comment]
It's going to be difficult to change this specific command, as it involves working with upstream Ironic who may not want to alter the base functionality. However I think we may be able to add a parallel ESI command - something like `openstack esi baremetal console connect` - that does this. We'll take a look!

**Comment by tzumainn** [comment]
https://github.com/CCI-MOC/python-esiclient/pull/60/files/41b5b70293dc574053c748897565afcaa0912cbe..cd90e4fe5e2115e3ef13bfb056c145d4df483332
