### ISSUE TITLE
Various problems in our support of floating ip addresses

### ISSUE THREAD

**Issue by naved001** [CCI-MOC/esi#463]
For a tenant to use floating IP on their private network requires:

1. The controllers to be configured on the private network's VLAN
2. A network bridge created on all the controllers for that private vlan.

This is all done manually and a bit clumsy. Not sure what the right thing to do is but it feels like it's an issue.

---
(Edits by @larsks)

Our current solution is problematic in several ways:

1. It requires manual intervention by a system administrator (that is, not someone with openstack admin privileges, but someone with direct `root` access to the controllers).

  I think (@tzumainn disagrees) that this, by itself, is contrary to our vision for ESI. We expect a smooth, automated process, but here we have something that will immediately block almost anyone starting to work with ESI.

2. Our manual workaround violates the isolation of private networks: by attaching all the networks to the same bridge in the global network namespace:

    - If two tenants happent to pick the same address range we will have a conflict, and
    - This configuration permits a tenant to route traffic to private networks belonging to other tenants. That's both unexpected and a security concern.

3. Our workaround relies on manually editing files, which opens up many possibilities for errors. We are also making some changes that will not persist across a reboot, which means when we next reboot a controller we will break floating ip access that is currently working.

**Comment by tzumainn** [comment]
I don't know if there's a great automated alternative; OpenStack handles floating IPs through magic that happens directly on the controllers. The only option I see is providing operators with an ansible playbook that automates all of this configuration (similar to the post-install playbooks that Danni wrote).

**Comment by tzumainn** [comment]
I guess I never updated this issue, but it's since been determined that the only *actual* operator step needed is to add the VLAN to the controller switch ports; as a result one solution is to simply pre-add every possible assignable VLAN (which is configured in neutron).

**Comment by tzumainn** [comment]
This is resolved with: https://github.com/CCI-MOC/ops-issues/issues/1153
