### ISSUE TITLE
Open up ports on controllers to allow for serial console

### ISSUE THREAD

**Issue by tzumainn** [CCI-MOC/esi#464]
ESI nodes all specify a unique port that allows for serial console access; however these ports need to be opened. What's the best way to do this?

**Comment by tzumainn** [comment]
@naved001 what's the best (persistent) way to open up a bunch of ports? Basically it seems like we may want to pre-open the ports specified for the serial consoles for each node. Or is this a bad idea?

**Comment by naved001** [comment]
@tzumainn I think RHEL8/CentOS8 use [firewalld](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/configuring_and_managing_networking/using-and-configuring-firewalld_configuring-and-managing-networking) for managing firewall configuration and it can be persistent too.

We should open up the port for each associated server, and open the port every time a new server is registered. There's no way around it as far as I can tell.

@larsks any thoughts on this matter?

**Comment by larsks** [comment]
@naved001 I need some context. Is this issue here that for each new server managed by Ironic, we need to open a unique port on the server to enable serial console access?

**Comment by naved001** [comment]
> Is this issue here that for each new server managed by Ironic, we need to open a unique port on the server to enable serial console access?

@larsks yes

**Comment by larsks** [comment]
I think the best option would be to implement a dynamic firewall management abstraction (with an initial implementation for iptables, and maybe one for firewalld) that updates the kernel firewall configuration as necessary, just like docker/podman/libvirt/etc.

I think a reasonable fallback plan is to open a range of ports as @tzumainn suggested.

I would typically disable/remove firewalld, install the `iptables-services` package, and then configure the desired initial firewall in `/etc/sysconfig/iptables`.

**Comment by joachimweyl** [comment]
@tzumainn have you decided on what route you are going to use to resolve this issue?

**Comment by tzumainn** [comment]
Yep; it'll be the manual route for now, and a less prioritized issue for the future to see if we can implement what Lars described. I'll take care of the manual update today or tomorrow.
