### ISSUE TITLE
Look at esi-leap concurrency unit tests to verify they work as intended

### ISSUE THREAD

**Issue by tzumainn** [CCI-MOC/esi#47]
It was mentioned that these concurrency tests may not be reliable. They may be worth another look.

**Comment by DanNiESh** [comment]
One workaround is writing a test that uses a number of threads to call the method and test if the method is actually synchronized.

**Comment by tzumainn** [comment]
I *think* the current test does use multi-threading. The hard part is testing the 'actually synchronized' bit - how is that verified?

**Comment by gagansk** [comment]
@DanNiESh Please close this

**Comment by DanNiESh** [comment]
This issue is closed because we think current unit test is good to prove it's thread safe.
