### ISSUE TITLE
Deploy updated ESI-Leap to MOC ESI

### ISSUE THREAD

**Issue by tzumainn** [CCI-MOC/esi#478]
This involves packaging an updated version of ESI-Leap, and deploying it to MOC ESI.

**Comment by tzumainn** [comment]
@DanNiESh would you be able to take this, either this sprint or (more likely) next?

**Comment by DanNiESh** [comment]
Yep!

**Comment by DanNiESh** [comment]
Updated the esi-leap on MOC ESI to version 0.2.10
