### ISSUE TITLE
Find way to send email from MOC ESI using authenticated email address

### ISSUE THREAD

**Issue by DanNiESh** [CCI-MOC/esi#483]
An authenticated email address is required to send notification emails to certain email addresses

**Comment by DanNiESh** [comment]
Naved will look into updating MOC DMARC policy to legitimate the SMTP server on ESI dev server.

**Comment by joachimweyl** [comment]
@naved001 what is the status of [this](https://github.com/CCI-MOC/esi/issues/483#issuecomment-1821239022) research?

**Comment by naved001** [comment]
@joachimweyl I have not researched this yet.

**Comment by joachimweyl** [comment]
@naved001 I believe we now have SMTP setup for this. what are next steps?

**Comment by tzumainn** [comment]
Closed by https://app.zenhub.com/workspaces/moc-a--rh-sprint-workspace-62a210f69d42f600151deae0/issues/gh/cci-moc/esi/529
