### ISSUE TITLE
Fix error message if an offer is claimed for its entire duration twice

### ISSUE THREAD

**Issue by tzumainn** [CCI-MOC/esi#484]
Steps to reproduce:

* create an offer with infinite duration
* claim the offer without specifying duration (thus making it infinite); this is lease A
* claim the offer again the same way; this is lease B

The second claim will result in a "Attempted to create lease resource with an invalid Start Time and End Time. Start Time must be strictly less than End Time." error message, likely because esi-leap will set the end time to right before lease A starts

**Comment by joachimweyl** [comment]
@skanthed What is the status of this issue?
if we are partially done please break this into multiple issues and complete the piece that is done.
if no work was done please push to the next sprint.
And of course if it is done please close :)

**Comment by tzumainn** [comment]
Taking this

**Comment by tzumainn** [comment]
https://github.com/CCI-MOC/esi-leap/pull/151
