### ISSUE TITLE
Release new python-esiclient with orchestrator commands and update ESI documentation

### ISSUE THREAD

**Issue by tzumainn** [CCI-MOC/esi#487]
These commands need to be released and documented.

**Comment by joachimweyl** [comment]
@tzumainn what is the status of this issue? Please push it to the next sprint if you don't think it will be completed.

**Comment by tzumainn** [comment]
It'll be delayed - I've moved it!

**Comment by tzumainn** [comment]
New python-esiclient released: https://pypi.org/project/python-esiclient/

Last step is to update the readthedocs documentation

**Comment by tzumainn** [comment]
PR created for documentation: https://github.com/CCI-MOC/esi/pull/500
