### ISSUE TITLE
Set quota on floating IPs on our current deployment.

### ISSUE THREAD

**Issue by naved001** [CCI-MOC/esi#492]
2 per project should be plenty.

We [already figured out quotas on VLANs](https://github.com/CCI-MOC/esi/issues/118#issuecomment-901347949) per project and we should also set that on projects (if we aren't already doing that).

**Comment by tzumainn** [comment]
I've set this manually for now. I still need to figure out how to configure this parameter in tripleo (or possible in a post-deploy ansible playbook).

**Comment by tzumainn** [comment]
I did this by updating the Neutron conf file on each controller; there's a quota section:

[quotas]
quota_port=500
quota_security_group=10
quota_network_gateway=5
quota_packet_filter=100
quota_floatingip=2

**Comment by naved001** [comment]
I made this change on the new deployment too.
