### ISSUE TITLE
Add password to BIOS setup to prevent tenant users from making BIOS changes

### ISSUE THREAD

**Issue by tzumainn** [CCI-MOC/esi#499]
Giving tenant users BIOS access has a lot of risks; it's better to just protect it from them.

We may want to do the following:

* add a BIOS password to one node
* verify that the node can still inspect/clean/provision normally
* if everything works, add to the rest of the nodes

**Comment by tzumainn** [comment]
I manually set a BIOS password, and verified that deploying/cleaning still worked. I think setting a BIOS password should be fine.

**Comment by hakasapl** [comment]
Okay, I will plan to implement this post-shutdown before we open up ESI to users

**Comment by hakasapl** [comment]
BIOS password has been added to all ESI fx2 nodes
