### ISSUE TITLE
Allow ESI-Leap to specify a default owner change duration which is configurable

### ISSUE THREAD

**Issue by tzumainn** [CCI-MOC/esi#50]
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200974017553249/1200974134173825) by [Unito](https://www.unito.io)

**Comment by tzumainn** [comment]
This request seems like it only works in a GUI. A CLI can't really default a value, as a user can't adjust it - and assuming a blank value means a certain time span is risky.

**Comment by joachimweyl** [comment]
no longer needed
