### ISSUE TITLE
Some nodes given to OKD have issues

### ISSUE THREAD

**Issue by tzumainn** [CCI-MOC/esi#506]
Some of the nodes given to OKD have issues. I've looked into each and solved some; however there are 10 nodes which I can't figure out what to do with:

* MOC-R4PAC21U37-S3B - nic seems to not be cabled up                                                                                                     
* MOC-R4PAC21U37-S3C - ipxe initialising devices... ok then exits                                                                                        
* MOC-R4PAC21U35-S1A - some old pxe version?      
* MOC-R4PAC21U35-S1C - some old pxe version?      
* MOC-R4PAC21U35-S3A - some old pxe version? 
* MOC-R4PAC22U35-S3A - ipxe initialising devices... ok then exits
* MOC-R4PAC24U37-S1B - Error: Te 1/27/2 Port is part of a non-default VLAN. 
* MOC-R4PAC24U31-S3C - Error: No such port in Vlan, config ignored Te 1/22/3; maybe exists for second NIC, but PXE only tries first NIC
* MOC-R4PAC24U31-S3D - Error: No such port in Vlan, config ignored Te 1/22/4; maybe exists for second NIC, but PXE only tries first NIC
* MOC-R4PAC22U33-S1A - won't turn on, even from idrac (before: won't boot from hard drive after provisioning) 

There were also a bunch of nodes which would provision "successfully", but wouldn't boot into the image; I solved that by changing the order of hard drive priority in the BIOS, but let me know if there was a better solution.

**Comment by tzumainn** [comment]
@hakasapl @naved001 in case you have some ideas on what to do about some of these errors

**Comment by tzumainn** [comment]
A few more:

MOC-R4PAC24U31-S3A - Error: Te 1/22/1 Port is part of a non-default VLAN.\r\n% Error: Port is in Layer-2 mode Te 1/22/1.
MOC-R4PAC21U35-S1B - provisioned, but can't ping; its baremetal port has mac a8:99:69:84:47:2f which is mapped to 1/13/2 in Ironic, but on the switch the mac is mapped to 1/13/3
MOC-R4PAC21U35-S3B - provisioned, but can't ping; its baremetal port has mac a8:99:69:84:48:9d which is mapped to 1/14/2 in Ironic, but on the switch the mac is mapped to 1/13/1

**Comment by hakasapl** [comment]
Merged into [this issue](https://github.com/CCI-MOC/ops-issues/issues/1354)
