### ISSUE TITLE
Add script and procedure for testing that nodes added to ESI actually work

### ISSUE THREAD

**Issue by tzumainn** [CCI-MOC/esi#507]
Sometimes nodes added to ESI have issues when a user attempts to actually use them (for example, metalsmith). Adding a script/procedure for testing these nodes would be very very helpful.

**Comment by tzumainn** [comment]
We should also test that `local_gb`> 0

**Comment by tzumainn** [comment]
@hakasapl I'm currently running this script against all the nodes that are unassigned. If a node fails, should I put it into maintenance, so it's easy to see that there's an issue?

**Comment by hakasapl** [comment]
Yes, that probably makes the most sense.

**Comment by tzumainn** [comment]
Okay, all nodes that have failed inspection or cleaning are now in maintenance

**Comment by tzumainn** [comment]
https://github.com/CCI-MOC/esi-pilot/pull/52

**Comment by tzumainn** [comment]
PR created; script has been run against unassigned ESI nodes, and failing nodes have been put in maintenance. A separate issue has been created to look at those nodes.

**Comment by joachimweyl** [comment]
@tzumainn can you please link the separate issue?

**Comment by tzumainn** [comment]
Yep! https://github.com/CCI-MOC/esi/issues/511
