### ISSUE TITLE
Explore Ironic introspection data and how it's pushed up into Ironic node metadata

### ISSUE THREAD

**Issue by tzumainn** [CCI-MOC/esi#508]
There is interest in exposing additional node data in Ironic; it's worth investigating what data Ironic introspection actually grabs, and whether that data can be pushed into the Ironic node

**Comment by tzumainn** [comment]
```
{
  "inventory": {
    "interfaces": [
      {
        "name": "eth5",
        "mac_address": "24:8a:07:1e:85:a1",
        "ipv4_address": "192.168.11.53",
        "ipv6_address": "fe80::c0d8:1bb:d410:b5a2%eth5",
        "has_carrier": true,
        "lldp": null,
        "vendor": "0x15b3",
        "product": "0x1015",
        "client_id": null,
        "biosdevname": "p5p2"
      },
      {
        "name": "eth3",
        "mac_address": "cc:c5:e5:d5:31:8b",
        "ipv4_address": null,
        "ipv6_address": null,
        "has_carrier": false,
        "lldp": null,
        "vendor": "0x14e4",
        "product": "0x168e",
        "client_id": null,
        "biosdevname": "em4"
      },
      {
        "name": "eth1",
        "mac_address": "cc:c5:e5:d5:31:7e",
        "ipv4_address": null,
        "ipv6_address": null,
        "has_carrier": false,
        "lldp": null,
        "vendor": "0x14e4",
        "product": "0x168e",
        "client_id": null,
        "biosdevname": "em2"
      },
      {
        "name": "eth4",
        "mac_address": "24:8a:07:1e:85:a0",
        "ipv4_address": "192.168.11.105",
        "ipv6_address": "fe80::382a:5b4b:4c9:7f2b%eth4",
        "has_carrier": true,
        "lldp": null,
        "vendor": "0x15b3",
```

**Comment by tzumainn** [comment]
@naved001 I've pasted some introspection data for a node for reference.

It looks like we can add introspection rules through the introspection CLI: https://docs.openstack.org/ironic-inspector/latest/user/usage.html#actions

Is there something in the introspection data above that you might want added to the node data? If so, I can work on two things:

* testing introspection rules to see if inspection pushes up that information to the node properly
* creating a script to update already inspected nodes (since we can't re-inspect them without cleaning, etc)

**Comment by naved001** [comment]
> Is there something in the introspection data above that you might want added to the node data?

CPU model may be of interest to people. In the past people have also queried for servers based on CPU frequency so I think those 2 items will be useful

```
    "cpu": {
      "model_name": "Intel(R) Xeon(R) CPU E5-4669 v4 @ 2.20GHz",
      "frequency": "3000.0000",
```

**Comment by tzumainn** [comment]
PR for the introspection rules created: https://github.com/CCI-MOC/esi-pilot/pull/53

I've also run a one-time script to update all nodes in ESI with this CPU information
