### ISSUE TITLE
Update ESI-Leap CLI to make node properties searchable

### ISSUE THREAD

**Issue by tzumainn** [CCI-MOC/esi#515]
After adding node properties to the CLI return values, the next step is to make them searchable so users can find nodes/leases/offers that match what they're looking for.

This change should be made to lease list, offer list, node list

I think this change can be made entirely on the client-side, because that makes it more flexible if we want to change the syntax later

**Comment by tzumainn** [comment]
https://github.com/CCI-MOC/python-esileapclient/pull/57

**Comment by joachimweyl** [comment]
@skanthed it looks like this will not finalize this sprint. can we break this into 2 issues, one that can be closed for this sprint and one that continues the work into next sprint?
