### ISSUE TITLE
Some nodes provision, but don't boot from the hard drive

### ISSUE THREAD

**Issue by tzumainn** [CCI-MOC/esi#517]
NERC reported that some of their nodes provisioned but failed to boot. It looks like these nodes all had two partitions - "Embedded SATA Port Disk B" and "Embedded SATA Port Disk A" - with B set higher in the boot order; when this happens, the node would fail to boot from hard drive C.

Changing the order allows the boot to complete; enabling hard-disk failover does the same thing. Is there a way we can configure this en masse for the nodes?

**Comment by hakasapl** [comment]
Yes, we should at least be able to set failover on all the nodes. I will take a look this week

**Comment by hakasapl** [comment]
HDD failover has been enabled on all ESI fx2 nodes
