### ISSUE TITLE
Setup automated ESI emails

### ISSUE THREAD

**Issue by tzumainn** [CCI-MOC/esi#519]
The following should be sent:

* periodic "these are your nodes"
* node expiration warnings

**Comment by tzumainn** [comment]
Danni's work for this is done; waiting on https://github.com/CCI-MOC/esi/issues/483

**Comment by tzumainn** [comment]
Hakan has shown me how to send emails; I'll work on this next!

**Comment by tzumainn** [comment]
@naved001 @hakasapl kinda curious about your thoughts: how should we get the relevant email addresses here? Most usernames in the MOC are email addresses - although there are one or two that came from ColdFront yet are somehow not. Or should we associate each project with an email address? This would mean we would need to ask for an email when creating a project (and update those already in ESI).

**Comment by hakasapl** [comment]
I would think we get a 'mail' attribute from SSO login. How can that be accessed? @knikolla?

**Comment by knikolla** [comment]
> I would think we get a 'mail' attribute from SSO login. How can that be accessed? @knikolla?

You can update the keystone federation mappings to read the `email` attribute provided from SSO and store it in the email field of the user. https://docs.openstack.org/keystone/latest/admin/federation/mapping_combinations.html#mappings-examples

Alternative, you can make an API call to ColdFront or Keycloak to fetch the email for a given user.

**Comment by tzumainn** [comment]
... and it turns out we already get the email attribute for the user; I just didn't pay attention. Whoops!

Okay, so it sounds like we would want notifications to go to all users in a project, and not have an email per project?

**Comment by hakasapl** [comment]
Yeah, definitely each user in a project

**Comment by tzumainn** [comment]
Okay - here are some emails I can generate. This one is a report of all leased nodes; I was thinking maybe this is sent out every Monday morning?

```
You are receiving this reminder email because you have leased nodes in the MOC ESI. If you have any unused nodes, please cancel those leases.

NODE                          LEASE START TIME                        LEASE END TIME                         
MOC-R4PAC21U25-S1             2023-09-14T17:37:52.468046              9999-12-31T23:59:59.999999             
MOC-R4PAC21U13-S3             2023-09-14T17:52:20.541715              9999-12-31T23:59:59.999999             
MOC-R4PAC21U21-S3             2023-09-22T15:29:29.841664              9999-12-31T23:59:59.999999             
oct4-17                       2023-10-27T15:39:01.853844              9999-12-31T23:59:59.999999             
MOC-R4PAC04U33                2024-06-03T16:50:37.977683              9999-12-31T00:00:00                     
MOC-R4PAC04U27-S1             2024-07-05T17:29:54.545500              2024-07-06T00:00:00                     
MOC-R4PAC04U25-S1             2024-07-05T17:31:13.460409              2024-07-13T00:00:00        
```

The other is a list of expiring leases - leases that will expire within three days. I was thinking that this could be checked and send out nightly:

```
You are receiving this reminder email because you have leased nodes in the MOC ESI that will expire soon. Please contact the MOC ESI administrators if you would like to extend these leases.

NODE                          LEASE START TIME                        LEASE END TIME                         
MOC-R4PAC04U27-S1             2024-07-05T17:29:54.545500              2024-07-06T00:00:00            
```

Thoughts?

**Comment by tzumainn** [comment]
PR for email script created: https://github.com/CCI-MOC/esi-pilot/pull/69

Once that's merged, the final step will be to create periodic jobs sending out these emails.

**Comment by tzumainn** [comment]
The email script has been created. The final step is to figure out what emails should be sent, and how often. The two easily supported emails are:

* a reminder email that details what nodes are being leased by a user
* an "upcoming lease expiration" email that mentions that a user's nodes will expire within X days (X is configurable)

The README (https://github.com/CCI-MOC/esi-pilot/blob/main/scripts/README.md) details some possible templates; I guess what I need is:

* what should the exact wording of these emails be?
* how often should the script sending these emails be run? (if a user has no leased nodes or expiring nodes, they won't get an email)
* should I notify people in the esi channel that they can start expecting these emails?

@hakasapl @msdisme thoughts?

**Comment by hakasapl** [comment]
I think it makes sense to notify the ESI channel.

@tzumainn Is there any way to include which nodes are expiring or which nodes are on active leases in the emails? Maybe with templates like `{ nodelist }` or something in the body?

**Comment by tzumainn** [comment]
Ah, yep! Every email includes a list of the relevant nodes. For example:

---
<div class="gE iv gt" style="font-size: 0.875rem; cursor: auto; padding: 20px 0px 0px; color: rgb(34, 34, 34); font-family: &quot;Google Sans&quot;, Roboto, RobotoDraft, Helvetica, Arial, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><br class="Apple-interchange-newline">
esi@massopen.cloud via amazonses.com | esi@massopen.cloud via amazonses.com | 1:13 PM (1 minute ago) |   |  
-- | -- | -- | -- | --
esi@massopen.cloud via amazonses.com
to me | to me
to me

<br><hr>You are receiving this email because you are a user of the MOC ESI cluster. If you would like to stop receiving email you will need to delete your account by contacting<span> </span><a href="mailto:support@massopen.cloud" target="_blank" style="color: rgb(17, 85, 204);">support@massopen.cloud</a></div></div></div>esi@massopen.cloud [via](https://support.google.com/mail/answer/1311182?hl=en) amazonses.com 
1:13 PM (1 minute ago)
to me

You are receiving this reminder email because you have leased nodes in the MOC ESI. If you have any unused nodes, please cancel those leases.

NODE	LEASE START TIME	LEASE END TIME
MOC-R4PAC21U25-S1	2023-09-14T17:37:52.468046	9999-12-31T23:59:59.999999
MOC-R4PAC21U13-S3	2023-09-14T17:52:20.541715	9999-12-31T23:59:59.999999
MOC-R4PAC21U21-S3	2023-09-22T15:29:29.841664	9999-12-31T23:59:59.999999
oct4-17	2023-10-2 7T15:39:01.853844	9999-12-31T23:59:59.999999
MOC-R4PAC04U33	2024-06-03T16:50:37.977683	9999-12-31T00:00:00
MOC-R4PAC04U25-S1	2024-07-05T17:31:13.460409	2024-07-13T00:00:00

You are receiving this email because you are a user of the MOC ESI cluster. If you would like to stop receiving email you will need to delete your account by contacting [support@massopen.cloud](mailto:support@massopen.cloud)

**Comment by tzumainn** [comment]
![email](https://github.com/CCI-MOC/esi/assets/1280178/c0d108f5-357b-4582-83dc-17460716026b)

**Comment by msdisme** [comment]
I'll do a pass at messages, initially in google doc.

**Comment by joachimweyl** [comment]
@msdisme is this something I can take off your plate?

**Comment by msdisme** [comment]
Lets go ahead with the letters as proposed.

**Comment by tzumainn** [comment]
Done! The lease reminder email will be sent out once per week on Monday, while the lease expiration email will be sent every day (but only to people with leases that are expiring withing 5 days).
