### ISSUE TITLE
Can ESI support Infiniband?

### ISSUE THREAD

**Issue by tzumainn** [CCI-MOC/esi#535]
This may be something users are looking for, so figuring this out would be nice.

**Comment by tzumainn** [comment]
@naved001 Looking at the code, it looks like some functionality exists and some does not; does any of this seem irrelevant? Any other issues I may have missed?

* DHCP on an infiniband network: this should just work (https://opendev.org/openstack/ironic/commit/8f251134e85e07880725413b461c4e6ab9f67a31)
* ML2 integration - can we pass partition keys similarly to vlans? if the segmentation_id can take a partition key value, in theory it would be passed to networking-ansible, and then we would just need an infiniband switch driver to do the appropriate configuration? (update: the segmentation_id needs to be an integer, so this won't work)
* the big question: how would we handle an environment that involves both an ethernet network and an infiniband network? Ironic needs to move nodes to the cleaning/provisioning network, and there's only one.

**Comment by naved001** [comment]
@tzumainn I don't have much to add besides saying that those are good questions! I wish we could borrow infiniband hardware to do some tests. I will read up some more about infiniband and then I will have some meaningful feedback.

**Comment by tzumainn** [comment]
Had a discussion during the demo meeting
