### ISSUE TITLE
These nodes fail provisioning

### ISSUE THREAD

**Issue by tzumainn** [CCI-MOC/esi#552]
* MOC-R4PAC22U17-S3
* MOC-R4PAC22U15-S3
* MOC-R4PAC22U15-S1

I monitored the console for one, and it seemed to error when trying to bring up a network interface for pxe boot; strange, because inspection previously worked

**Comment by joachimweyl** [comment]
@hakasapl are we targeting for this to finish this sprint? If not, please push it out to next sprint.

**Comment by msdisme** [comment]
@hakasapl will work with techsquare to bring them up to speed so they may do this work.

**Comment by hakasapl** [comment]
Merged into [this issue](https://github.com/CCI-MOC/ops-issues/issues/1354)
