### ISSUE TITLE
Obtain node and provision for dev installation of ESI

### ISSUE THREAD

**Issue by tzumainn** [CCI-MOC/esi#553]
We are now missing a dev installation of ESI. It's probably ideal to have one.

TripleO is now deprecated, so I'd suggest using devstack (with Ironic enabled) and seeing if that works. This may be of use for others to test ESI more easily as well.

* Obtain a node through the MOC ESI
* Provision it with a devstack-compatible OS

**Comment by skanthed** [comment]
Provisioned a node - https://docs.google.com/document/d/1RwqDzSDl-7Y8RuGz8tILN1QibOpNlHXn3zkXa8UZ0qY/edit#heading=h.x4eja88uix7n
