### ISSUE TITLE
Evaluate images for UEFI compatibility

### ISSUE THREAD

**Issue by tzumainn** [CCI-MOC/esi#556]
While testing UEFI boot, it was discovered that not all images naturally work with UEFI; for example, our centos9-stream image does not while our ubuntu image does. We should double check all our images for UEFI compatibility, and then have follow-up tasks to remediate those images which have issues.

**Comment by tzumainn** [comment]
After testing, the following images work in UEFI mode:

* ubuntu
* debian
* centos8-stream

The following do not:

* centos9-stream
* fedora

@naved001 do we care about these images for UEFI boot? Maybe the centos9-stream image?

**Comment by naved001** [comment]
> Maybe the centos9-stream image?

@tzumainn probably. We should probably have at least one of centos/rhel/fedora type image. But I wouldn't rush to prepare these images unless we have specific requirements.

btw, centos8-stream has [reached EOL](https://blog.centos.org/2023/04/end-dates-are-coming-for-centos-stream-8-and-centos-linux-7/) so it's unlikely people would want to use this and we should probably not recommend that image.

**Comment by tzumainn** [comment]
Okay - I'll create an issue to create a compatible centos9-stream image, and close this one.
