### ISSUE TITLE
Formalize deployment of configuration and files necessary for UEFI support

### ISSUE THREAD

**Issue by tzumainn** [CCI-MOC/esi#557]
* undo some of the changes done from https://docs.openstack.org/ironic/latest/install/configure-pxe.html#ipxe-setup and see if they're actually necessary
* update neutron dnsmasq.conf (but see if tripleo can configure this for us)
* create custom ipxe.efi image (and document the creation)

That might actually be it!

**Comment by joachimweyl** [comment]
@tzumainn what is the next step for this? Is this part of an epic we could add it to?

**Comment by tzumainn** [comment]
Ah, the steps are pretty much as I said in the description. I just need to find time to do it!

I'm not sure what the best epic match would be, to be honest.

**Comment by tzumainn** [comment]
Looks like the changes in https://docs.openstack.org/ironic/latest/install/configure-pxe.html#ipxe-setup aren't actually needed.

**Comment by tzumainn** [comment]
https://github.com/CCI-MOC/esi-pilot/pull/66
