### ISSUE TITLE
Create ESI GUI use case document

### ISSUE THREAD

**Issue by tzumainn** [CCI-MOC/esi#562]
There seems to be considerable interest in the ESI GUI again; a use case document will help ensure everyone is on the same page. The cases covered should include:

* viewing leased nodes
* viewing available nodes and leasing ones that match certain parameters
* provisioning nodes
* opening up a secure console to a node
* viewing reports on node leases

**Comment by tzumainn** [comment]
I've started a use case document here: https://docs.google.com/document/d/1kGu--dV449m4paNm7ggakpLv6JXiFJstVy3BPbP2DV0/edit

Feel free to start filling stuff in; if you're not sure what it should look like, I can also do a few use cases first.

I was going to add examples of use cases I've seen recently, but I think this one will be different, as a description of the flow is important. I'd say start a use case, put in as much information as you think is relevant, and then we'll work together to figure out if there's a way to present the information that makes it easier for others to picture.

**Comment by tzumainn** [comment]
First draft of the use case document is complete; any feedback is welcome!

**Comment by joachimweyl** [comment]
@tzumainn are there specific people you would like to provide feedback?

**Comment by tzumainn** [comment]
To be honest, I kind of have no idea! Whoever might have a direct interest in an ESI GUI, I guess.

**Comment by joachimweyl** [comment]
@msdisme, @waygil can you review the document above please? And feel free to tag anyone else you think might provide useful insight for ESI GUI.

**Comment by waygil** [comment]
Reviewed and added a general comment on whether we want more fine grained control for the Tenent User and Node Owner roles.

**Comment by msdisme** [comment]
Reviewed and added a some nitpicky comments :-)

**Comment by joachimweyl** [comment]
@msdisme @tzumainn has made the changes you and @waygil suggested. Are there more changes needed or is this document ready to be uploaded to GH?

**Comment by joachimweyl** [comment]
@tzumainn what is the desired location for this documentation? do you have a repository of ESI documentation? Please move it there and close this issue.

**Comment by tzumainn** [comment]
Done!
