### ISSUE TITLE
Create centos9-stream image compatible with UEFI and Legacy boot

### ISSUE THREAD

**Issue by tzumainn** [CCI-MOC/esi#564]
Current one only works with Legacy

**Comment by skanthed** [comment]
# Steps to Create and Configure the CentOS 9 Image compatible with UEFI and Legacy boot

### Step 1: Install Disk Image Builder
Use the following command to install Disk Image Builder:

```
pip install diskimage-builder
```

### Step 2: Set Up the Environment Variables
Ensure that both the `ELEMENTS_PATH` and `_LIB` environment variables are correctly set:

```
export _LIB=/path/to/diskimage_builder
export ELEMENTS_PATH=$_LIB/elements
```

These paths should point to the location where Disk Image Builder is installed and where its elements are located.

### Step 3: Create the CentOS 9 Image
Use the following command to create the CentOS 9 image:

```
IMG=centos9-stream-uefi-legacy
DIB_RELEASE=9-stream disk-image-create centos vm dhcp-all-interfaces bootloader grub2 -o $IMG -p linux-firmware
```

This command will build a CentOS 9 image with the specified options.

### Step 4: Verify the Image Contents (Optional)
After creating the image, you can verify its contents using `guestfish` to ensure that the necessary files (e.g., kernel, initramfs) are included:

```
guestfish --ro -a <image-name>.qcow2 -i

><fs> ls /boot
```

This will display the contents of the `/boot` directory in the image, confirming that the kernel and initramfs files are present.

### References
For more details on Disk Image Builder and how it works, refer to the following documentation:

- [Disk Image Builder Documentation](https://docs.openstack.org/diskimage-builder/latest/)
- [Creating Images for Ironic in OpenStack](https://docs.openstack.org/ironic/latest/user/creating-images.html)

**Comment by skanthed** [comment]
It's been tested on both legacy and uefi boot.
