### ISSUE TITLE
Investigate large number of IPMI errors in Ironic conductor log

### ISSUE THREAD

**Issue by tzumainn** [CCI-MOC/esi#569]
There are frequent errors as follows:

```
2024-07-01 13:04:48.768 7 WARNING ironic.drivers.modules.ipmitool [req-b20f2fc1-3324-4eda-83f1-2bbbbbdbefbd - - - - -] IPMI Error encountered, retrying "ipmitool -I lanplus -H ... -R 1 -N 5 -f /tmp/tmpv3nt66ba power status" for node 6e584c65-4245-4a7d-bdb7-e893738e85e2. Error: Unexpected error while running command.
Command: ipmitool -I lanplus -H ...t -R 1 -N 5 -f /tmp/tmpv3nt66ba power status
Exit code: 1
Stdout: ''
Stderr: 'Error: Unable to establish IPMI v2 / RMCP+ session\n': oslo_concurrency.processutils.ProcessExecutionError: Unexpected error while running command.
```

Cursory examination shows that this node is in maintenance mode, so it's maybe not unexpected; however this creates a TON of log noise. Is there a way to turn this check off?

**Comment by tzumainn** [comment]
It looks like the vast majority of errors comes from three nodes:

* 10.2.14.101 - MOC-R4PAC08U19-S1 - can't ping
* 10.2.14.102 - MOC-R4PAC08U19-S3 - can't ping
* 10.2.11.72 -MOC-R4PAC24U13-S3 -can ping, but ipmitool has Error

I thought putting them in `manage` might stop the IPMI checking, but apparently not. I am betting enroll will do it; however, there's no way to do that through the API. I could delete them and re-add them and leave them in `enroll` while also marking them as in maintenance. @hakasapl what do you think?

**Comment by tzumainn** [comment]
Oh, the other option is to just shrug and let the errors continue; it's not THAT big a deal.

**Comment by hakasapl** [comment]
@tzumainn if putting them in maintenance mode doesn't work I guess just delete and re-add for now, I think those nodes are/need to be replaced

**Comment by tzumainn** [comment]
the nodes have been deleted and recreated, and the mass errors seem to have gone away. thanks!
