### ISSUE TITLE
Update `esi node list` to include additional values required by UI

### ISSUE THREAD

**Issue by tzumainn** [CCI-MOC/esi#571]
The UI display of nodes currently calls both `esi node list` and Ironic node list, merging the information together. However the REST API behind `esi node list` already grabs Ironic nodes and fetches some of the needed information. We should:

* update ESI Leap so that the node list call includes all of the needed Ironic information
* update the ESI UI to eliminate the call to Ironic node list

**Comment by tzumainn** [comment]
Reopening because I assume this will also require a change in the esi-ui

**Comment by ajamias** [comment]
This is being blocked because the MOC's esi-leap service is not updated to include the power state information, target provision state, and future lease and offer information. Once that is done then a PR can be created for the UI.

**Comment by tzumainn** [comment]
This should now be unblocked!
