### ISSUE TITLE
Do a cleanup pass on the ESI UI tenant user panels

### ISSUE THREAD

**Issue by tzumainn** [CCI-MOC/esi#572]
Let's take a step back, look at the UI, and ensure the needed information is front and center for tenant users. For example, a user probably does not need to see the node UUID; however the expiration date of the lease is pretty important.

We should probably wait to do this until the bulk of the tenant user panels are up and functional.

**Comment by ajamias** [comment]
https://docs.google.com/document/d/1kcCdko0J1zjy5oj_0kIOr4FllrPuHnmYVLlMpDavvmY/edit

**Comment by ajamias** [comment]
Will also update provisioning wizard to look like network manage wizard, and clean up code

**Comment by ajamias** [comment]
Should we also add the Apache 2 header in the files and linters?

**Comment by tzumainn** [comment]
I talked to @ajamias and @sheldor1510 ; anshul will take over the development of this, but austin will add his thoughts regarding the refactoring.

Austin, did you have any other comments on the changes proposed by Anshul in his doc?

**Comment by ajamias** [comment]
Also, to unclutter the controller.js files, I think the catch statements should go in their corresponding function in the service.js files wherever applicable.

**Comment by ajamias** [comment]
@sheldor1510 how's it going with this issue? Let me know if you need any help

**Comment by sheldor1510** [comment]
> @sheldor1510 how's it going with this issue? Let me know if you need any help

@ajamias I'm around halfway done with the node table update, will push something by tomorrow and will let you know if I have any doubts, thanks!
