### ISSUE TITLE
Generate a list of current ESI users and generate a regular report for review

### ISSUE THREAD

**Issue by msdisme** [CCI-MOC/esi#581]
This came up because Red Hat was being charged for systems when the users were not yet ready for them. 

As a person who is paying for systems shared via ESI, I would like a way to generate the current state of the ESI systems being used and associated with my billing so that I may ensure that machines are allocated correctly.

As a person making decisions about ESI  loans, I would like a report of all current loans so that I may make better decisions about usage. 

- [ ] Generate a current list of users and systems and details about the start and end time and date of the lease,
- [ ] create a process to generate such a report on demand. Initially, this can be the entire list, and access can be limited so that people with billing responsibility may use the data as needed.   Ideally this would either be generated automatically and dropped into a private location  (private repository or google sheet)

Longer term, as part of billing for bare metal we will want to revisit how the reports are generated  and reported to users.

**Comment by tzumainn** [comment]
@msdisme just for clarity, does "current" mean active leases at the time of the report?

**Comment by msdisme** [comment]
Yes.  Is there a way to generate upcoming lease requests ?

**Comment by tzumainn** [comment]
Yep - well, for clarity there's no such thing as a lease 'request' per se; however, there are leases that are targeted for the future and which are in the database. But for this specific report, it sounds like you just want a list of all currently active leases, which is easy enough!

**Comment by tzumainn** [comment]
Here's the output of `openstack esi lease list -f csv`:

[leases.csv](https://github.com/user-attachments/files/16334054/leases.csv)

All you need is access to the admin user, which I believe naved and hakan also have.

**Comment by joachimweyl** [comment]
@msdisme does this output look good or do we want it formated in a specific way?

**Comment by tzumainn** [comment]
Note that this command will only list currently active leases; if you want expired/deleted leases, you have to add `--status any`. Let me know if this fulfills this request, or there's a more specific query desired!

**Comment by joachimweyl** [comment]
This meets original request, will open a new issue if there are further details needed.
