### ISSUE TITLE
These ESI nodes have issues provisioning

### ISSUE THREAD

**Issue by tzumainn** [CCI-MOC/esi#583]
These four nodes can be cleaned, but provisioning fails. I took a look at one, and it looks like the first NIC is misconfigured, as it doesn't appear on the switch's mac address table. The second NIC works, which explains the behavior (both NICs are automatically configured when cleaning, but by default only the first NIC is configured when attaching a network to a node).

* MOC-R4PAC24U03-S3
* MOC-R4PAC22U31-S1A
* MOC-R4PAC24U37-S3C
* MOC-R4PAC24U31-S1A

**Comment by hakasapl** [comment]
Merged into [this issue](https://github.com/CCI-MOC/ops-issues/issues/1354)
