### ISSUE TITLE
Create bare metal topology view in ESI ui

### ISSUE THREAD

**Issue by tzumainn** [CCI-MOC/esi#586]
If you instantiate a UI (or use the esi.massopen.cloud dashboard), you can click on Network > Network Topology and see an... error screen. Search for the feature though, and you'll see what it's supposed to look like.

It would be really nice to use the same tool to implement a bare metal topology view. I think the exact same UI framework/tool can be used; all that's needed is to generate and pass in a different topology based one what we can from Ironic and ESI-Leap APIs. For example, something like:

Node > Node ports > Neutron ports > Network

There would be added complicated bits; for example, if the Neutron port is a trunk port we'd want to show trunk port information, and if it has a floating IP attached we'd want to show that as well.

**Comment by ajamias** [comment]
Would we rather have the flat topology or the connected graph topology?

**Comment by tzumainn** [comment]
I think the graph one is cooler :) when it works, you can drag around the bits and have the graph rearrange itself.
