### ISSUE TITLE
The MOC ESI needs an updated ubuntu image

### ISSUE THREAD

**Issue by tzumainn** [CCI-MOC/esi#589]
We need an updated ubuntu image - I believe the latest is 22.04 - that works like the current ubuntu image (password login disabled, ssh key injected through cloud-init).

**Comment by tzumainn** [comment]
Surbhi has created an ubuntu 22.04 image; I've tested it and made it public. Thanks!

**Comment by skanthed** [comment]
# Steps to Create and Configure the Ubuntu Image

### Step 1: Create a Cloud-Init Configuration File (Optional)
This step is optional as some settings might be managed by default in the image creation process.

```yaml
#cloud-config
ssh_pwauth: false
disable_root: true
```

### Step 2: Install Disk Image Builder
Use the following command to install Disk Image Builder:

```bash
pip install diskimage-builder
```

### Step 3: Create the Ubuntu Image
Use the following command to create the Ubuntu image:

```bash
disk-image-create -a amd64 -o <image-name> ubuntu baremetal dhcp-all-interfaces grub2 cloud-init
```

# Additional Notes:

### Environment-Specific Configuration
Cloud-init uses data sources like Ec2 or ConfigDrive to gather metadata necessary for instance configuration, such as network settings and SSH keys. In some environments, the default data source (e.g., Ec2) might not be compatible with your OpenStack environment, leading to issues like network misconfiguration.

### Check the Current Data Source Configuration
Boot your instance or use guestfish to access the image.

```bash
ls /etc/cloud/cloud.cfg.d/
cat /etc/cloud/cloud.cfg.d/91-dib-cloud-init-datasources.cfg
```

This command will show the current data source configuration. Look for lines specifying `datasource_list`.

### Modify the Data Source (If Necessary)
If the data source is set to Ec2 and you're in an OpenStack environment, edit the configuration:

```bash
edit /etc/cloud/cloud.cfg.d/91-dib-cloud-init-datasources.cfg
```

Change the data source to ConfigDrive:

```yaml
datasource_list: [ ConfigDrive, None ]
```

This change tells cloud-init to use ConfigDrive for fetching metadata, which is more suitable for OpenStack environments.

### Step 7: Reboot the Image
Reboot the image to apply the changes. After the reboot, the network and other configurations should work as expected.

####  References: 
For more details on disk-image builder or cloud-init data sources and how they interact with OpenStack, refer to the following documentation:

- [OpenStack Disk Image Builder - Cloud-Init Datasources](https://docs.openstack.org/diskimage-builder/latest/elements/cloud-init-datasources/README.html)
- [Cloud-Init Data Sources Documentation](https://cloudinit.readthedocs.io/en/21.2/topics/datasources.html)
- [Creating Images for Ironic in OpenStack](https://docs.openstack.org/ironic/latest/user/creating-images.html)
