### ISSUE TITLE
Add ability to attach/detach floating IPs in the UI

### ISSUE THREAD

**Issue by tzumainn** [CCI-MOC/esi#592]
We can provision and network a node in the UI; attaching a floating IP is the next step.

**Comment by ajamias** [comment]
Will we want to have a feature where the user can specify a port forwarding to associate to a floating ip too?

**Comment by tzumainn** [comment]
Yeah, that's definitely a good idea!

**Comment by ajamias** [comment]
If the user wants to perform this attach/detach, the user will press a button next to the search bar at the top of the page. After pressing, there will be a wizard with 2 pages (actually its called steps): attach and detach. The attach page will show have a dropdown button to select from the floating IPs that are not already attached, a dropdown button of neutron port names to attach to, and optionally create a list of port forwardings. The detach page will have a dropdown button to select from the floating IPs that are already attached in the form: 192.168.123.7 (Neutron port name). The way that the frontend will retrieve these floating IPs, is by using [getFloatingIps()](https://github.com/openstack/horizon/blob/78d33c213f5c76ed056bceff46e906d0927bac9b/openstack_dashboard/static/app/core/openstack-service-api/network.service.js#L60C14-L60C30). You can see the "return" value [here](https://github.com/openstack/openstacksdk/blob/master/openstack/network/v2/floating_ip.py). There are two ways you can go about actually sending the request to attach/detach. 1: use the openstack [network api](https://docs.openstack.org/api-ref/network/v2/index.html#floating-ips-floatingips). 2: create your own endpoints and write python logic to attach/detach.
