### ISSUE TITLE
Update UI to let users know that a networking operation is taking place

### ISSUE THREAD

**Issue by tzumainn** [CCI-MOC/esi#593]
A network attach operation takes more than a few seconds, but the UI returns instantaneously with no indication that the operation is taking place. If we can get a "progressing" bar that would be great. I suspect that may be difficult to do for now however, since there's no API we can call to show that a networking operation is taking place (I think); failing that, perhaps a message will suffice for now.

**Comment by skanthed** [comment]
@tzumainn this issue is done it has both progress bar and the message. Works fine. I need to create PR but waiting for -https://github.com/CCI-MOC/esi-ui/pull/16 to get merged because it will again have conflicts because same file and same line have been changed.

**Comment by skanthed** [comment]
https://github.com/CCI-MOC/esi-ui/pull/17
