### ISSUE TITLE
Test conversion of bootc image and deployment on a bare metal node

### ISSUE THREAD

**Issue by tzumainn** [CCI-MOC/esi#595]

**Comment by ajamias** [comment]
I read up on a way to provision a node using the image: quay.io/centos-bootc/centos-bootc:stream9.
Instructions are here: https://github.com/osbuild/bootc-image-builder?tab=readme-ov-file#-prerequisites.

First I populated the config.toml file with the content:
```
[[customizations.user]]
name = "alice"
password = "bob"
key = "ssh-rsa AAA ... user@email.com"
groups = ["wheel"]
```
Here are the commands I ran to build the image:
```
sudo dnf install -y osbuild-selinux
sudo podman pull quay.io/centos-bootc/centos-bootc:stream9
mkdir output
sudo podman run \
    --rm \
    -it \
    --privileged \
    --pull=newer \
    --security-opt label=type:unconfined_t \
    -v $(pwd)/config.toml:/config.toml:ro \
    -v $(pwd)/output:/output \
    -v /var/lib/containers/storage:/var/lib/containers/storage \
    quay.io/centos-bootc/bootc-image-builder:latest \
    --type qcow2 \
    --local \
    quay.io/centos-bootc/centos-bootc:stream9
```

After the image is built, it should be in a file in ./output/qcow2/disk.qcow2. Then I uploaded this image to the OpenStack Glance service:
```
openstack image create --disk-format qcow2 --file ./output/qcow2/disk.qcow2 centos9-stream-bootc
```

Once you have the image in Glance, you can provision a node with that image. I used the metalsmith CLI.

**Comment by tzumainn** [comment]
Is it possible to create the image with `cloud-init` enabled? In theory, I think that would allow generic images that anyone could use. Could you give that a whirl, and test that metalsmith will embed the user's ssh key?

**Comment by ajamias** [comment]
create the image with `cloud-init` as in after uploading the image to glance? I'm doing some reading and I not understanding how `cloud-init` would "create" an image. From what I understand, the a node would have to be deploying (metalsmith is already ran), and cloud-init configures (set ssh keys, etc) during the deploying process. Also, metalsmith already has an option to pass in a user's ssh key.

**Comment by ajamias** [comment]
Reading more, I notice that Metalsmith's `instance_config.CloudInitConfig` configures the node using `cloud-init` for ssh keys, user data, and meta data.

**Comment by tzumainn** [comment]
That's not actually quite right - the images we have in glance right now all have cloud-init enabled; that's how ssh keys get passed in when we provision nodes with metalsmith.

**Comment by ajamias** [comment]
Right, but the metalsmith cli can only pass ssh keys, not user data or metadata seen here: https://github.com/openstack/metalsmith/blob/dd5dc4e471576e05b0bd42c79508f51f6bc1b4e1/metalsmith/_cmd.py#L67

**Comment by tzumainn** [comment]
We're not creating an AMI image, but I think https://docs.redhat.com/en/documentation/red_hat_enterprise_linux/9/html/using_image_mode_for_rhel_to_build_deploy_and_manage_operating_systems/creating-bootc-compatible-base-disk-images-with-bootc-image-builder_using-image-mode-for-rhel-to-build-deploy-and-manage-operating-systems#creating-ami-images-by-using-bootc-image-builder-and-uploading-it-to-aws_creating-bootc-compatible-base-disk-images-with-bootc-image-builder describes a possible configuration that might work for this?

**Comment by ajamias** [comment]
Just to clarify, I am assuming the user that wants to provision a baremetal node with a bootc image. The user has podman, their own containerfile, and bootc-image-builder installed. If that is the case, then the user can enable cloud-init themselves in a containerfile, build it, and then follow the instructions I gave above.

**Comment by ajamias** [comment]
So the use case that you're more interested in is the one where the user only has a link to a (docker, quay.io, etc) bootc image. Then there should be some interface either CLI and/or GUI that takes the image name and converts, enables cloud-init, and uploads automatically. And then the user can use metalsmith/GUI to provision using that uploaded image.

**Comment by tzumainn** [comment]
Not quite - the use case I'm interested in is where the ESI administrators are ultimately supplying the image (like we do for the bulk of the images right now). The process we go through to configure the image doesn't have to be simple, since it's not done often and we'd be the ones doing it. We don't need the image to be uploaded to glance automatically either.

Really, I just want to establish the procedure for us to convert the bootc image to a bare metal-ready image with cloud-init enabled.

**Comment by ajamias** [comment]
Ok I have a process to configure the image using cloud-init.

1. Create a cloud-config.cfg file with your configuration
```
#cloud-config

users:
  - default
  - name: ajamias
    ssh_authorized_keys:
      - ecdsa-sha2-nistp521 AAAAE2VjZHNhLXNoYTItbmlzdHA1MjEAAAAIbmlzdHA1MjEAAACFBAF+DsX2i+buBGtVmCvqGBDVbpKdmq2/sLnF06l1H90EHFLMR/RfvT+YXKm0ykKYvX3bl7bGYNal54WW5Ws2HfR6zgH4d4pV7mS6IRxt+68GI2BGRo2AR9v9tGQJ2hGwDgd17GxQpas4eV9pAVEEOCiQeNia0RznR8SBhG+xUQ2aBgeLkA== ajamias@fedora
    sudo: ALL=(ALL) NOPASSWD:ALL
```

2. Create a Containerfile with at least these lines
```
FROM quay.io/centos-bootc/centos-bootc:stream9 

COPY ./cloud-config.cfg /etc/cloud/cloud.cfg.d/

RUN dnf -y install cloud-init && \
    ln -s ../cloud-init.target /usr/lib/systemd/system/default.target.wants && \
    rm -rf /var/{cache,log} /var/lib/{dnf,rhsm}

CMD ["cloud-init", "init"]
```

3. Build the image
```
podman build -t centos9-stream-bootc .
mkdir output
sudo podman run \
	--rm \
	-it \
	--privileged \
	--pull=newer \
	--security-opt label=type:unconfined_t \
	-v $(pwd)/output:/output \
	-v /var/lib/containers/storage:/var/lib/containers/storage \
	quay.io/centos-bootc/bootc-image-builder:latest build \
	--type qcow2 \
	--local \
	localhost/centos9-stream-bootc:latest
```

4. Upload the image to OpenStack Glance
```
openstack image create --disk-format qcow2 --file ./output/qcow2/disk.qcow2 centos9-stream-bootc
```

5. Provision
```
metalsmith deploy <args>
```

**Comment by tzumainn** [comment]
Is it possible to do it without step 1 (or to not specify the ssh key in step 1)? Our goal is to make a generic image that anyone can boot with their ssh key embedded, without any other possible access mechanisms.

**Comment by ajamias** [comment]
Without specifying the ssh key in step 1, there is an option for cloud-init to read from the OpenStack [metadata service](https://docs.openstack.org/nova/latest/admin/metadata-service.html), however I think that having a cloud-config.cfg file is necessary for telling cloud-init where to look for data and metadata. What format is this generic image in? Like a Containerfile, quay.io, or qcow2, etc?

**Comment by tzumainn** [comment]
I'm almost positive that metalsmith/Ironic will handle passing in the ssh-key for the cloud-init stuff for you - https://opendev.org/openstack/metalsmith/src/branch/master/metalsmith/_cmd.py#L67-L70 (which leads into the Ironic API).

qcow2 would be fine!

**Comment by ajamias** [comment]
So we could keep step 1 except we remove all mentioned ssh keys, and the user can use the other config features that cloud-init provides, and just have metalsmith embed the ssh key that the user gives? Then steps 1-3 would produce the qcow2 image without the ssh key, but with all other cloud-init configuration, and then the ssh key would be embedded during provisioning right?

**Comment by ajamias** [comment]
Ok, I just did it and it works. I was able to ssh into the machine

**Comment by larsks** [comment]
@ajamias: @tzumainn pointed me at this issue, and I wanted to comment on a couple of things.

It's not necessary to symlink `cloud-init.target` into `/usr/lib/systemd/system/default.target.wants`: the `cloud-init` package includes a systemd [generator](https://www.freedesktop.org/software/systemd/man/latest/systemd.generator.html), `/usr/lib/systemd/system-generators/cloud-init-generator` that will automatically enable `cloud-init.target` when appropriate.

It is also not necessary to provide a custom `cloud.cfg`; the `cloud-init` package includes a default `/etc/cloud/cloud.cfg` that among other things sets up the default `cloud-user` user.

The following `Containerfile` is sufficient:

```
FROM quay.io/centos-bootc/centos-bootc:stream9 

RUN dnf -y install cloud-init && \
    rm -rf /var/{cache,log} /var/lib/{dnf,rhsm}
```

With this configuration, the public key embedded in the cloud-init metadata provided by ironic will be used to configure the `cloud-user` user. You can see this data on an ironic-deployed system by mounting the config volume that ironic creates:

```
mount -oro LABEL=config-2 /mnt
```

And then looking at the `openstack/latest/meta-data.json` file. For example:

```
$ jq < /mnt/openstack/latest/meta_data.json
{
  "public_keys": {
    "0": "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCt6bEbDunOQuL72HrEIPpK2LBWpBcraSe6+r6ovGaiiIvquKclalJbr6Okotlz95o15M1pZnBCKQlnGhcwr2cZhrAy7lR1+vw5KnD9lN/yW/b7iuQusvC5rs2TDeH9IhPHHIMl4A2io0urAUXRJ2RlgDzSacSz4sspaq4I10GsWaVahs4gN+MyDde3tkkwUnWjGVYrFJSRP5crfMeftTphhcc/zSB3Z5wQ2wwog9FkaZIYOWnPYeSoPDBWVbJagctzRTkimYCoczY/YGxTliZj2uTpfxDZrYhlOL8dZxH2JfGzduIl4Zf3isdiykoFNOdTuhUe2+B9qoKf2WnIdBOH tzumainn@redhat.com"
  },
  "uuid": "0b5d1e1e-a038-4f7a-83e5-732cd51ef679",
  "name": "MOC-R8PAC23U28",
  "hostname": "MOC-R8PAC23U28",
  "launch_index": 0,
  "availability_zone": "",
  "files": [],
  "meta": {}
}
```
