### ISSUE TITLE
Deploy RHELAI/InstructLab on ESI

### ISSUE THREAD

**Issue by tzumainn** [CCI-MOC/esi#596]
* find the bootc image
* convert
* deploy and test

**Comment by ajamias** [comment]
Most steps are outline [here](https://github.com/RedHatOfficial/rhelai-dev-preview?tab=readme-ov-file#preparing-the-build-host). Here are the steps I took so far (the process takes ~1 hour):

First, create an account on redhat.com if not created already.

Register the host. The username and password are the same as the ones on your account on redhat.com 
```
sudo subscription-manager register --username <username> --password <password>
```

Install required packages
```
sudo dnf install git make podman buildah lorax -y
```

Clone the RHEL AI Developer Preview git repo
```
git clone https://github.com/RedHatOfficial/rhelai-dev-preview
```

Authenticate to the Red Hat registry ([Red Hat Container Registry Authentication](https://access.redhat.com/RegistryAuthentication)) using your redhat.com account.
```
podman login registry.redhat.io --username <username> --password <password>
```

Make the images that RHEL AI will use.
```
make instruct-nvidia && make vllm && make deepspeed
```

Make the RHEL AI image. The name of it is called "nvidia-bootc:latest"
```
make nvidia FROM=registry.redhat.io/rhel9/rhel-bootc:9.4 REGISTRY=<your-registry> REGISTRY_ORG=<your-org-name> SSH_PUBKEY=<path-to-pubkey>
```

Push this image to an image registry
```
podman push ${REGISTRY}/${REGISTRY_ORG}/nvidia-bootc:latest --creds <username>:<password>
```

Build the qcow2 image
```
mkdir -p output
sudo podman run \
	--rm \
	-it \
	--privileged \
	--pull=newer \
	--security-opt label=type:unconfined_t \
	-v $(pwd)/output:/output \
	-v /var/lib/containers/storage:/var/lib/containers/storage \
	quay.io/centos-bootc/bootc-image-builder:latest build \
	--type qcow2 \
	--local \
	$(REGISTRY)/$(REGISTRY_ORG)/nvidia-bootc:latest
```

Currently, I have the qcow2 image. When I try to `openstack image create --disk-format qcow2 --file ./output/qcow2/disk.qcow2 rhelai-nvidia-bootc`, it gives me an SSL exception.

**Comment by tzumainn** [comment]
Interesting - do you have the exact error message if you run image creation with `--debug`?

**Comment by ajamias** [comment]
Hmm I guess it works when I'm connected to ethernet

**Comment by ajamias** [comment]
Here is an updated procedure:

# Build the image

First, create an account on redhat.com if not created already.

Install required packages
```
sudo dnf install subscription-manager git make podman buildah lorax -y
```

Register the host. The username and password are the same as the ones on your account on redhat.com
```
sudo subscription-manager register --username <username> --password <password>
```

Clone the RHEL AI Developer Preview git repo
```
git clone https://github.com/RedHatOfficial/rhelai-dev-preview
```

Authenticate to the Red Hat registry ([Red Hat Container Registry Authentication](https://access.redhat.com/RegistryAuthentication)) using your redhat.com account.
```
podman login registry.redhat.io --username <username> --password <password>
```

Run `sudo ./build.sh`. (Change the arguments that fit your requirements)

build.sh:
```
#!/bin/bash

# 1. Create the prerequisite container images
make instruct-nvidia && \
make vllm && \
make deepspeed && \

# 2. Create the bootc container image (the SSH_PUBKEY argument is for root user access)
make nvidia FROM=registry.redhat.io/rhel9/rhel-bootc:9.4 REGISTRY=quay.io REGISTRY_ORG=ajamias1 SSH_PUBKEY="$(cat $HOME/.ssh/id_rsa.pub)" && \

# 3. (Optional) Use the previously created image and enable cloud-init
make cloud-nvidia BOOTC_IMAGE=quay.io/ajamias1/nvidia-bootc:latest REGISTRY=quay.io REGISTRY_ORG=ajamias1 && \

# 4. Use the previously created image and turn it into qcow2 format. The resulting qcow2 file will be in training/nvidia-bootc/build/qcow2/disk.qcow2 
make disk-nvidia DISK_TYPE=qcow2 BOOTC_IMAGE=quay.io/ajamias1/nvidia-bootc-cloud:latest BOOTC_IMAGE_BUILDER="quay.io/centos-bootc/bootc-image-builder build"
```
The output will be stored in `rhelai-dev-preview/training/nvidia-bootc/build`

# Deploy the image

Upload the image to OpenStack Glance
```
openstack image create --disk-format qcow2 --file ./rhelai-dev-preview/training/nvidia-bootc/build/qcow2/disk.qcow2 rhelai-nvidia-bootc-cloud
```

Use the metalsmith CLI to deploy this image on a baremetal node
```
metalsmith deploy --resource-class <resource_class> --image rhelai-nvidia-bootc-cloud --network <network ID or name> --candidate <node ID or name>
```

Assign a floating IP to one of that node's network port, and then you can `ssh root@<IP address>`

**Comment by tzumainn** [comment]
Is it possible to do this without passing in your ssh key while building the image (and passing it in with metalsmith instead)? Otherwise someone's ssh key will always be baked into the image, which is a security hole.

**Comment by ajamias** [comment]
I am pretty sure that the Makefile requires that the SSH_PUBKEY argument is supplied, but you could just supply an empty string

**Comment by tzumainn** [comment]
Okay - just for completeness's sake, could you do that and test provisioning passing in the ssh key through metalsmith?

**Comment by ajamias** [comment]
I created a new issue to request 2 GPUs for an ESI node here: #607

**Comment by ajamias** [comment]
> Okay - just for completeness's sake, could you do that and test provisioning passing in the ssh key through metalsmith?

The two changes I made is to set SSH_PUBKEY=\n, but it can be any non-zero length string, and add the --ssh-public-key argument to the metalsmith command.

I just deployed this and I can ssh into it as cloud-user, and when I try to ssh as root it says `Please login as the user "cloud-user" rather than the user "root".` So it works!

**Comment by tzumainn** [comment]
Awesome!

**Comment by joachimweyl** [comment]
@ajamias what are the next steps or is this issue ready to be closed?

**Comment by tzumainn** [comment]
I think this issue can be closed.
