### ISSUE TITLE
Deploy ESI UI plugin to MOC ESI production

### ISSUE THREAD

**Issue by tzumainn** [CCI-MOC/esi#598]

**Comment by tzumainn** [comment]
Created initial esi-ui package

**Comment by tzumainn** [comment]
Deployment completed successfully; need to formalize a method of doing so.

**Comment by joachimweyl** [comment]
@tzumainn can we link to the PR where deployed?
Next time I suggest 2 issues, one for deployment and 1 for formalizing method.

**Comment by tzumainn** [comment]
Yep - but this is taking much longer than I expected due to an unexpected issue when logging in with SSO rather than username/password

**Comment by tzumainn** [comment]
https://github.com/CCI-MOC/esi-ui/pull/23 fixes the issue; once that's merged, I can try the production deploy again.

**Comment by tzumainn** [comment]
Deployed; custom Horizon Dockerfile PR created at https://github.com/CCI-MOC/esi-pilot/pull/74
