### ISSUE TITLE
Determine what OperateFirst needs to do once they acquire a node

### ISSUE THREAD

**Issue by tzumainn** [CCI-MOC/esi#60]
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200974017553249/1200974047367236) by [Unito](https://www.unito.io)

**Comment by tzumainn** [comment]
Needs to boot an installer through:

* pxe boot
* boot from virtual media

**Comment by tzumainn** [comment]
BMC proxy may be needed

**Comment by joachimweyl** [comment]
no longer needed
