### ISSUE TITLE
Review ways of making ESI UI easier to understand

### ISSUE THREAD

**Issue by tzumainn** [CCI-MOC/esi#601]
* a dashboard page with more information (prominent nodes, quotas, etc)?
* when a user wants to provision a node, are the steps apparent and obvious?
* ??

**Comment by skanthed** [comment]
I think the steps for provisioning nodes are minimal and easy to understand.
### Enhanced Node Actions Dropdown:
Instead of placing actions in a dropdown, frequently used actions like Provision, Power On, and Manage Networks should be directly available in the node list for quicker access. This reduces unnecessary clicks and improves the user experience.

### RHEL Image Provisioning Option:
Add a feature to allow users to select and provision RHEL-based images directly through the UI. This would expand the system’s flexibility for environments requiring RHEL.

### State Description Tooltips:
Adding tooltips next to each action (e.g., Delete Lease, Manage Floating IPs) would help new users understand the purpose of each action. This can reduce confusion and improve usability.

### Quota Management:
Implement quota tracking on the dashboard to monitor resource usage (e.g., CPU, memory, disk) and prevent over-provisioning. This would be particularly helpful when provisioning high-demand resources, such as RHEL AI images, ensuring that users stay within their allocated limits and can plan resource utilization accordingly.
### Visual Indicators for Provision States:
Use colored labels or icons to easily identify the node state:

Manageable: Gray/blue with a gear icon (available, not yet provisioned).
Available: Green label or checkmark (ready for provisioning).
Active: Bold green or server icon with checkmark (provisioned and active).

**Comment by skanthed** [comment]
@joachimweyl @tzumainn If the user specified particular needs that you think should be done. Can you let them know here?

**Comment by skanthed** [comment]
> Good start! Here are my comments:
> 
> > I think the steps for provisioning nodes are minimal and easy to understand.
> > ### Enhanced Node Actions Dropdown:
> > Instead of placing actions in a dropdown, frequently used actions like Provision, Power On, and Manage Networks should be directly available in the node list for quicker access. This reduces unnecessary clicks and improves the user experience.
> 
> If there are a lot of actions, will this clutter the UI?


Since the "Delete Lease" action is already present in the main action bar (next to "Provision Nodes" and "Unprovision Nodes"), you can remove "Delete Lease" from the Actions dropdown. 
Since "Manage Floating IPs" is an essential action after provisioning, moving it to the top action bar (next to "Provision Nodes") would make it more accessible
> 
> > ### RHEL Image Provisioning Option:
> > Add a feature to allow users to select and provision RHEL-based images directly through the UI. This would expand the system’s flexibility for environments requiring RHEL.
> 
> Is there a reason to call out RHEL images specifically?


As we discussed I just mentioned this to have the functionality to able to provision RHEL AI image through UI.
> 
> > ### State Description Tooltips:
> > Adding tooltips next to each action (e.g., Delete Lease, Manage Floating IPs) would help new users understand the purpose of each action. This can reduce confusion and improve usability.
> > ### Quota Management:
> > Implement quota tracking on the dashboard to monitor resource usage (e.g., CPU, memory, disk) and prevent over-provisioning. This would be particularly helpful when provisioning high-demand resources, such as RHEL AI images, ensuring that users stay within their allocated limits and can plan resource utilization accordingly.
> 
> What quota are we comparing against? OpenStack only knows about OpenStack resource quotas; do we have quotas for CPU/memory/disk?
> 
> > ### Visual Indicators for Provision States:
> > Use colored labels or icons to easily identify the node state:
> > Manageable: Gray/blue with a gear icon (available, not yet provisioned). Available: Green label or checkmark (ready for provisioning). Active: Bold green or server icon with checkmark (provisioned and active).
> 
> This makes a lot of sense!
> 
> I'd also like you to go through the current provisioning workflow through the UI, from scratch (including not having an SSH key uploaded yet, and assigning a floating IP in the end). What steps does a user need to take, and can we simplify that workflow? The goal is to have a new user be able to do full provisioning through the UI (ssh key and floating IP included), and then simply be able to ssh into their node from the command line without ever having to download the CLIs. What can we do to simplify that process?

Done, Will update on this.
> 
> @ajamias can you add your thoughts here as well?

**Comment by ajamias** [comment]
> ### Quota Management:
> 
> Implement quota tracking on the dashboard to monitor resource usage (e.g., CPU, memory, disk) and prevent over-provisioning. This would be particularly helpful when provisioning high-demand resources, such as RHEL AI images, ensuring that users stay within their allocated limits and can plan resource utilization accordingly.

@tzumainn is there a way to get billing information from the currently existing APIs? Would this information be appropriate for a lessee to see?

> I'd also like you to go through the current provisioning workflow through the UI, from scratch (including not having an SSH key uploaded yet, and assigning a floating IP in the end). What steps does a user need to take, and can we simplify that workflow? The goal is to have a new user be able to do full provisioning through the UI (ssh key and floating IP included), and then simply be able to ssh into their node from the command line without ever having to download the CLIs. What can we do to simplify that process?
> 
> @ajamias can you add your thoughts here as well?

Would an "Upload ssh key from file" button and "create new floating IP" button be appropriate for this?

**Comment by skanthed** [comment]
> > > ### Quota Management:
> > > Implement quota tracking on the dashboard to monitor resource usage (e.g., CPU, memory, disk) and prevent over-provisioning. This would be particularly helpful when provisioning high-demand resources, such as RHEL AI images, ensuring that users stay within their allocated limits and can plan resource utilization accordingly.
> > 
> > 
> > @tzumainn is there a way to get billing information from the currently existing APIs? Would this information be appropriate for a lessee to see?
> 
> Currently I don't think we have automated billing, so there's no place to get this information, unfortunately.
> 
> > > I'd also like you to go through the current provisioning workflow through the UI, from scratch (including not having an SSH key uploaded yet, and assigning a floating IP in the end). What steps does a user need to take, and can we simplify that workflow? The goal is to have a new user be able to do full provisioning through the UI (ssh key and floating IP included), and then simply be able to ssh into their node from the command line without ever having to download the CLIs. What can we do to simplify that process?
> > > @ajamias can you add your thoughts here as well?
> > 
> > 
> > Would an "Upload ssh key from file" button and "create new floating IP" button be appropriate for this?
> 
> That makes a lot of sense! I kinda of wonder if it's possible to make it part of the provisioning wizard.

Would it be possible to provide users with an option in the provisioning wizard to automatically attach a floating IP during the node provisioning process? For users who prefer manual control, we could still keep the existing process as an alternative.

**Comment by tzumainn** [comment]
> > > 
> > > 
> > > Would an "Upload ssh key from file" button and "create new floating IP" button be appropriate for this?
> > 
> > 
> > That makes a lot of sense! I kinda of wonder if it's possible to make it part of the provisioning wizard.
> 
> Would it be possible to provide users with an option in the provisioning wizard to automatically attach a floating IP during the node provisioning process? For users who prefer manual control, we could still keep the existing process as an alternative.

I think that would be a really good idea!

**Comment by skanthed** [comment]
Hi @tzumainn and @ajamias,

Just wanted to check in—do either of you have any additional suggestions or items that should be added here?

**Comment by skanthed** [comment]
## Steps for a New User to Provision a Node in the UI:

1. **Navigate to the Node Info Page**:
   - Log into the OpenStack dashboard.
   - Go to **Project > ESI > Nodes** to view the assigned nodes.

2. **Open the Provision Nodes Wizard**:
   - Select the node that has been assigned to you.
   - Click on the **Provision Nodes** button to open the provisioning wizard.

3. **Upload or Select SSH Key**:
   - In the wizard, you'll be prompted to provide an **SSH Key**. If you haven’t uploaded a key yet:
     - Navigate to **Project > Compute > Key Pairs** and upload or create a new SSH key.
     - After uploading the key, return to the **Provision Nodes** wizard and select the uploaded key.

4. **Select Image and Network**:
   - Choose the **Image Name** for the node (e.g., RHEL, Ubuntu).
   - Attach a network by selecting it from the **Network** dropdown.
 

5. **Review and Submit**:
   - Once you've filled in all the fields (image, network, SSH key), review the information and click **Submit** to complete the provisioning.

6. **Assign a Floating IP**:
   - After provisioning, assign a floating IP to the node to enable SSH access:
    - In the **Actions** menu next to your node, click on **Manage Floating IPs** to open the wizard.
     - Select the port and floating IP you want to associate with the node.



7. **SSH into the Node**:
   - Once done. Use the assigned **floating IP** and the uploaded **SSH key** to access the node from your terminal:
     ```bash
     ssh -i /path/to/key.pem user@<floating-IP>
     ```

**Comment by tzumainn** [comment]
Thanks! My main takeaways from this are:

* add colors to states
* simplify the provisioning process; you mentioned floating IPs, but I think bringing in the ssh key upload into our wizard would make sense as well

Are there others I'm missing? @ajamias @sheldor1510 do you have thoughts?

**Comment by skanthed** [comment]
> * simplify the provisioning process; you mentioned floating IPs, but I think bringing in the ssh key upload into our wizard would make sense as well

Including the SSH key upload directly in the provisioning wizard for sure. However, we should also provide an option for users to select an existing key from Key Pairs if they have one already uploaded. This would give them flexibility to either upload a new key or use an existing one.

**Comment by tzumainn** [comment]
Created new issues for follow up work. Thanks!
