### ISSUE TITLE
Determine options for booting RHELAI images in ESI

### ISSUE THREAD

**Issue by tzumainn** [CCI-MOC/esi#603]
RHELAI engineers would like to boot using ISOs. What can we do?

* test ISOs
* test options for REALLY big ISOs (100GB)

**Comment by tzumainn** [comment]
ISO experiment was unsuccessful, but Austin successfully provisioned using a qcow2 image. We also received a qcow2 image from jeremy eder, and provisioned a machine that Thibault is using for tests. I'll check in with them again in a few days to see if things are going as expected.

**Comment by joachimweyl** [comment]
@tzumainn when you check in on [this issue](https://github.com/nerc-project/operations/issues/692), please update this issue as well.

**Comment by tzumainn** [comment]
https://github.com/CCI-MOC/esi/pull/617
