### ISSUE TITLE
Obtain 2 GPUs to test RHEL AI/InstructLab deployment on ESI node

### ISSUE THREAD

**Issue by ajamias** [CCI-MOC/esi#607]
I think the person to contact about this is @hpdempsey

**Comment by tzumainn** [comment]
I was about to say that there's no a100s available, but that's technically not true at the moment; MOC-R8PAC23U28 is unleased. This is the node that was originally allocated to OpenShiftBeta, but hardware issues led to the lease being canceled (and a different a100 assigned to the project).

So I guess maybe MOC-R8PAC23U28 is temporarily leasable, with the understanding that it would have to immediately be returned as soon as it's asked for - @hpdempsey would that be all right with you?

**Comment by tzumainn** [comment]
I believe Taj is doing this testing; closing this as out of date.
