### ISSUE TITLE
MOC-R4PAC24U35-S1A  has mismatches between the ironic mac addresses and what shows up on the switch

### ISSUE THREAD

**Issue by tzumainn** [CCI-MOC/esi#618]
The node has the following mac addresses in Ironic:

* 10:7d:1a:9c:6d:81
* 10:7d:1a:9c:6d:84 

However, if you attach networks to the node, the mac addresses you see on the switch are:

* 10:7d:1a:9c:6d:83
* 10:7d:1a:9c:6e:54

**Comment by tzumainn** [comment]
MOC-R4PAC24U35-S3B appears to be affected as well. Both nodes are on MOC-R4PAC24-SW-TORS-A; is it possible that the switch is affected somehow?

**Comment by tzumainn** [comment]
Nevermind; this appears to be a bizarre image issue. Our fedora image apparently shifts the mac address by two somehow... ? I'll put in a separate issue for that.

**Comment by hakasapl** [comment]
Also, I would not assume the switch's mac table is reliable. The NICs on the node side are a weird passthrough thing so it may not be exposing the mac address correctly
