### ISSUE TITLE
Update UI to add status colors

### ISSUE THREAD

**Issue by tzumainn** [CCI-MOC/esi#621]
One way to make the ESI UI more comprehensible is to add status colors. I'm thinking the following:

* Maintenance: Green if False, Red if True
* Provision State: Green if active, Red if any failure state, Brown if non-active and non-failure state, blue if it's transitioning from one state to another
* Lease duration: Red if the lease expires within a week, Orange if it expires within a month, Green if the expiration date is greater than a month (or the user simply owns the node)

**Comment by skanthed** [comment]
https://github.com/CCI-MOC/esi-ui/pull/29
