### ISSUE TITLE
Update provisioning UI to streamline the workflow

### ISSUE THREAD

**Issue by tzumainn** [CCI-MOC/esi#622]
The provisioning UI workflow can be simplified as follows:

* Add a floating IP drop down; choices can be "None", or "Create", or any already existing floating IP that is not being used. If the user is already at quota, then "Create" should not be available (and maybe a message should be displayed)
* Allow the user to upload an ssh key or specify an existing one (or simply not use an ssh key)

If a user selects the top "Provision Nodes" option to provision multiple nodes, then the floating IP drop down should be blanked out, with a message that floating IP management will have to be done post-provisioning.

**Comment by skanthed** [comment]
- https://github.com/CCI-MOC/esi-ui/pull/27  
-  https://github.com/CCI-MOC/esisdk/pull/11

**Comment by tzumainn** [comment]
All PRs merged
