### ISSUE TITLE
In the ESI UI, add colors to an offer's availabilities

### ISSUE THREAD

**Issue by tzumainn** [CCI-MOC/esi#647]
Right now, the offer list makes it difficult to distinguish between offers which are immediately available and those which are only available in the future. Adding a color to the Availabilities would make this clearer - perhaps green if it's available now, and brown if it's available in the future?

**Comment by skanthed** [comment]
@tzumainn Should we make the color green if the availability is on the same day as the current date, or should we include a specific time comparison as well?

**Comment by tzumainn** [comment]
I would say green if it's available right away - i.e., the user can claim it and immediately start using it.

**Comment by skanthed** [comment]
https://github.com/CCI-MOC/esi-ui/pull/31
