### ISSUE TITLE
Determine requirements for RH OpenStack deployment

### ISSUE THREAD

**Issue by tzumainn** [CCI-MOC/esi#649]
* How can we test it out?
* Does it support Ironic?
* How does neutron manage switches (in the absence of ml2-ansible networking)?
* Is there a RH contact to talk to about upgrades (from OSP wallaby)?
* Can we migrate Ironic data without destroying node info?

**Comment by tzumainn** [comment]
we'll break this task into smaller bits after some initial investigation and discussion

**Comment by skanthed** [comment]
https://docs.redhat.com/en/documentation/red_hat_openstack_services_on_openshift/18.0

**Comment by skanthed** [comment]
**2. Does it support Ironic?**

Ironic is supported, the docs just need lots of work and that is underway right now.
Bare metal provisioning uses Metal3, which leverages Ironic on the backend. However, this is currently for static networking only, without any ML2 plugin integration.
ML2 plugin integration is being focused only for BMaaS workloads.


It mean bare metal provisioning through Metal3 uses static networking without ML2 plugin integration. This means that network configurations must be pre-defined and cannot be dynamically adjusted by Neutron during provisioning.
BMaaS workloads that require dynamic networking will not function without ML2 plugin support.


**3. How does Neutron manage switches (in the absence of ML2-Ansible networking)?**


Without ML2-Ansible networking, Neutron cannot dynamically manage switches.
Network configurations must be static and predefined in the current setup.
Work is underway to enable tools like networking-generic-switch and networking-baremetal for switch configuration, but these are not integrated capabilities yet.
ML2 is supported plugin-wise, but containers need to be patched with customer-supplied ML2 plugins.

We might be able to patch the container and test these features.

There are two distinct workflows:

- One for BMaaS nodes, which ML2 plugins can manage dynamically for networking.
- Another for nodes hosting VMs, which are managed by Metal3/Ironic independently.


**4. Is there a RH contact to talk to about upgrades (from OSP wallaby)?** 

Yes, For ironic specifically, the redhat openstack ironic team on irc or slack.


**5. what is the typical upgrade path from wallaby?** 

Typical Upgrade Path:

- The upgrade process follows the "adoption" model:
- Set up a new control plane on OpenShift.
- Migrate data (including Ironic node information) into the new cluster.
- Start the new containers with the migrated data.

the documentation called "adoption" which is still under some work.


**6. Can we migrate Ironic data without destroying node info?** 
Yes, the "adoption" model allows this.
The "adoption" model is designed to preserve Ironic node information during migration.

Steps:

- Configure the new cluster on OpenShift.
- Migrate data, including Ironic node details, from the old cluster (e.g., OSP Wallaby).
- Start the new containers using the migrated data, ensuring continuity and no data loss.

**Comment by tzumainn** [comment]
This is really great info - thanks! I'm going to close this issue, and modify some of the other ones based on what you have here.
