### ISSUE TITLE
Explore keylime attestation with real TPM hardware

### ISSUE THREAD

**Issue by DanNiESh** [CCI-MOC/esi#65]
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200974017553249/1200974076033482) by [Unito](https://www.unito.io)

**Comment by DanNiESh** [comment]
Enabled TPM on dell-2 node. TPM1.2 is installed on dell-2. But the current workflow only support tpm2.0.

**Comment by naved001** [comment]
does that mean those dells are no good?

**Comment by DanNiESh** [comment]
> does that mean those dells are no good?

I think there's a way to update TPM firmware from 1.2 to 2.0. But I'm not sure.

**Comment by naved001** [comment]
I looked up the dell website for updates for this specific dell server, and couldn't see an upgrade to tmp2.0

https://www.dell.com/support/home/en-us/product-support/servicetag/0-ZGpPVGI2RDhBYmZpNXRzdDVGNVN4UT090/drivers

**Comment by DanNiESh** [comment]
Will ask keylime folks if there's any technical issue with using tpm1.2.

**Comment by pjd-nu** [comment]
It looks like only systems from 2015 or newer can upgrade to TPM 2.0: https://www.dell.com/support/kbdoc/en-us/000132583/dell-systems-that-can-upgrade-from-tpm-version-1-2-to-2-0

**Comment by gagansk** [comment]
@naved001 to check if he can find machines to address this issue.

**Comment by tzumainn** [comment]
It was mentioned that the recently donated Wayfair machine may have these chips.

**Comment by tzumainn** [comment]
Moving to "To do" as Hakan is installing TPM chips on oct4-07 and oct4-13

**Comment by DanNiESh** [comment]
https://docs.google.com/document/d/1GN9Us4-rMP2Q0nxWaknWb_qEtg0OHBwxwT05JNFzSJ0/edit?usp=sharing

**Comment by DanNiESh** [comment]
> https://docs.google.com/document/d/1GN9Us4-rMP2Q0nxWaknWb_qEtg0OHBwxwT05JNFzSJ0/edit?usp=sharing

I've updated this doc with a bug report.
