### ISSUE TITLE
Make it easier to detach networks

### ISSUE THREAD

**Issue by larsks** [CCI-MOC/esi#660]
Typically, an ESI node only has a single network connection. It should be able to run `openstack esi network detach` with knowing the port name. Either:

1. Running `openstack esi network detach <node>`, when there is only a single port associated with the node, should detach that port, or
2. Introduce a `--all` option so that `openstack esi network detach --all <node>` will detach all networks from the node

**Comment by tzumainn** [comment]
Strange - 1. should already be happening (https://github.com/CCI-MOC/esisdk/blob/main/esi/lib/nodes.py#L257-L272); what behavior do you see in that case?

**Comment by larsks** [comment]
Oh, is it? I was following https://esi.readthedocs.io/en/latest/usage/openshift.html which sets `--port` explicitly every time, so I assumed it was required.

**Comment by tzumainn** [comment]
Yeah, we updated it a while back; we set it explicitly in the documentation just in case people do additional things with their networks.
