### ISSUE TITLE
Create esi resource list view

### ISSUE THREAD

**Issue by tzumainn** [CCI-MOC/esi#77]
This should show all resources a user is involved with, along with their current status

**Comment by tzumainn** [comment]
I thought this would be doable solely in the CLI; however, getting things like project names requires admin access to Keystone. It may make more sense to make a new API endpoint in esi-leap - something like NodesController - that queries for Ironic nodes and then displays them joined together with lease and offer information.

**Comment by betaredex** [comment]
https://github.com/CCI-MOC/esi-leap/pull/82

**Comment by betaredex** [comment]
https://github.com/CCI-MOC/esi-leap/pull/85

**Comment by betaredex** [comment]
https://github.com/CCI-MOC/esi-leap/pull/90

https://github.com/CCI-MOC/python-esileapclient/pull/31
