### ISSUE TITLE
No registrar ip/port flags in keylime tenant command

### ISSUE THREAD

**Issue by DanNiESh** [CCI-MOC/esi#79]
Registrar ip and port can be set in keylime.conf. But a non-admin user might not have access to the machine which the keylime CONF file sits on, so the ability to set the registrar as a flag in the tenant is essential.

**Comment by DanNiESh** [comment]
Keylime folks had a discussion that it would be nice if every option in keylime.conf could be set with environment variables.  https://github.com/keylime/enhancements/pull/49#discussion_r654570318

**Comment by ljmcgann** [comment]
This pr addresses the issue in Keylime
https://github.com/keylime/keylime/pull/704
