### ISSUE TITLE
Document Keylime Certificate Flushing Issue

### ISSUE THREAD

**Issue by ljmcgann** [CCI-MOC/esi#81]
There is currently an outstanding issue in the Keylime repo. https://github.com/keylime/keylime/issues/550

This issue affects us in that it requires a workaround by setting the check_ek_cert flag to False in the controller's CONF file.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200974017553249/1200974044300429) by [Unito](https://www.unito.io)

**Comment by joachimweyl** [comment]
@tzumainn with Leo no longer working this project is this still a priority or shall we close it?

**Comment by tzumainn** [comment]
I think we can close it.
