### ISSUE TITLE
Deploy openstack on the ESI HW

### ISSUE THREAD

**Issue by gagansk** [CCI-MOC/esi#94]
DoD:

larsks Create subtasks and dependencies for this issue.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200974017553249/1200974127253513) by [Unito](https://www.unito.io)

**Comment by tzumainn** [comment]
https://etherpad.opendev.org/p/QF_JXHTOgZSaRPMkqZKa

**Comment by larsks** [comment]
@tzumainn @DanNiESh @ljmcgann I've created a private repository at https://github.com/CCI-MOC/esi-pilot-cluster to host information related to this work. We've configured your ESI development host with access to the appropriate IPMI network; there's a doc in the repository with some information on that.
